In [1]:
import sys

print(sys.version)
print(sys.executable)

3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
c:\Users\mrdag\AppData\Local\Programs\Python\Python314\python.exe

In [ ]:

import numpy as np
import pandas as pd

numeric_columns = [
    "duration",
    "time_taken_by_user",
    "segment_character_per_second"
]

for column in numeric_columns:
    values = pd.to_numeric(df_raw[column], errors="coerce")

    print(f"\n--- {column} ---")
    print("Missing or non-numeric:", values.isna().sum())
    print("Zero values:", (values == 0).sum())
    print("Negative values:", (values < 0).sum())
    print("Positive infinity:", np.isposinf(values).sum())
    print("Negative infinity:", np.isneginf(values).sum())

    display(values.describe().to_frame("statistics"))

In [2]:
%pip install pandas numpy matplotlib seaborn openpyxl

Requirement already satisfied: pandas in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.4)
Requirement already satisfied: matplotlib in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.2)
Requirement already satisfied: seaborn in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.4.0)
Requirement already satisfied: cycler>=0.10 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.67.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.1)
Requirement already satisfied: packaging>=20.0 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.3)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: six>=1.5 in c:\Users\mrdag\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
import sys
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl

print("=" * 45)
print("JOSH TALKS AI — Q2 ENVIRONMENT CHECK")
print("=" * 45)

print("Python:", sys.version.split()[0])
print("Executable:", sys.executable)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Seaborn:", sns.__version__)
print("OpenPyXL:", openpyxl.__version__)

print("\nEnvironment setup successful!")

=============================================
JOSH TALKS AI — Q2 ENVIRONMENT CHECK
=============================================
Python: 3.14.7
Executable: c:\Users\mrdag\AppData\Local\Programs\Python\Python314\python.exe
Pandas: 3.0.6
NumPy: 2.5.4
Matplotlib: 3.11.2
Seaborn: 0.13.2
OpenPyXL: 3.1.5

Environment setup successful!

In [5]:
from pathlib import Path

# Locate dataset whether running from project root or inside notebooks/
data_candidates = [
    Path("data/raw/transcription_data.csv"),
    Path("../data/raw/transcription_data.csv"),
]
data_path = next((p for p in data_candidates if p.exists()), data_candidates[0])

print("File exists:", data_path.exists())
print("File path:", data_path.resolve())

File exists: True
File path: C:\Users\mrdag\OneDrive\Desktop\josh-talks-q2\data\raw\transcription_data.csv

In [6]:
import pandas as pd
from pathlib import Path

# Locate the original CSV without modifying it.
data_candidates = [
    Path("data/raw/transcription_data.csv"),
    Path("../data/raw/transcription_data.csv"),
]
data_path = next((p for p in data_candidates if p.exists()), data_candidates[0])

# Load the original dataset into a DataFrame.
# We will preserve df_raw as our reference for all later comparisons.
df_raw = pd.read_csv(data_path)

# Report the dataset dimensions.
print("Dataset loaded successfully.")
print("Number of rows:", df_raw.shape[0])
print("Number of columns:", df_raw.shape[1])

# Display the first five rows to verify the data loaded correctly.
display(df_raw.head())

Dataset loaded successfully.
Number of rows: 51783
Number of columns: 8

,user_id,recording_url,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second
0,71275781,https://storage.googleapis.com/joshtalks-data-...,इन जॉब में तो बहुत पैसे कमा है आपने,इन जॉब में तो बहुत पैसे कमा है आपने,No,2.94,15.00,9.18
1,71275800,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.96,14.26,3.13
2,71275813,https://storage.googleapis.com/joshtalks-data-...,तो उसमें एक मन एक मंत की सैल्वी उसमें आठ लिया...,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,Yes,4.83,20.85,7.87
3,71275842,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.45,8.46,6.67
4,71275856,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.27,11.65,11.11

In [7]:
# Inspect the dataset schema before making any cleaning decisions.

print("COLUMN NAMES")
for column in df_raw.columns:
    print(f"- {column}")

print("\nDATA TYPES")
display(df_raw.dtypes.to_frame(name="data_type"))

print("\nDATASET INFORMATION")
df_raw.info()

COLUMN NAMES
- user_id
- recording_url
- whisper_text
- user_text
- is_edited
- duration
- time_taken_by_user
- segment_character_per_second

DATA TYPES

                             data_type
user_id                          int64
recording_url                      str
whisper_text                       str
user_text                          str
is_edited                          str
duration                       float64
time_taken_by_user             float64
segment_character_per_second   float64

DATASET INFORMATION
<class 'pandas.DataFrame'>
RangeIndex: 51783 entries, 0 to 51782
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   user_id                       51783 non-null  int64
 1   recording_url                 51783 non-null  str
 2   whisper_text                  28681 non-null  str
 3   user_text                     51783 non-null  str
 4   is_edited                     51783 non-null  str
 5   duration                      51783 non-null  float64
 6   time_taken_by_user            51603 non-null  float64
 7   segment_character_per_second  51783 non-null  float64
dtypes: float64(3), int64(1), str(4)
memory usage: 3.2 MB

In [8]:
# AUDIT 1: Missing values and duplicate records
# This cell only measures data quality; it does not modify df_raw.

# 1. Summarize missing values in each column.
missing_audit = pd.DataFrame({
    "missing_count": df_raw.isna().sum(),
    "missing_percent": (
        df_raw.isna().mean() * 100
    ).round(2)
})

print("MISSING VALUE AUDIT")
display(missing_audit)

# 2. Count exact duplicate rows.
# Do not remove them until we understand whether they are genuine duplicates.
exact_duplicates = df_raw.duplicated().sum()

print(f"\nExact duplicate rows: {exact_duplicates:,}")

# 3. Check duplicate task identifiers using recording_url.
# This is a diagnostic only: the same recording might legitimately be reused.
duplicate_recordings = df_raw["recording_url"].duplicated(keep=False)

print(
    "Rows whose recording URL appears more than once:",
    f"{duplicate_recordings.sum():,}"
)

# 4. Inspect a few repeated recording URLs, if any.
display(
    df_raw.loc[
        duplicate_recordings,
        ["user_id", "recording_url", "user_text"]
    ].head(10)
)

MISSING VALUE AUDIT

                              missing_count  missing_percent
user_id                                   0             0.00
recording_url                             0             0.00
whisper_text                          23102            44.61
user_text                                 0             0.00
is_edited                                 0             0.00
duration                                  0             0.00
time_taken_by_user                      180             0.35
segment_character_per_second              0             0.00

Exact duplicate rows: 0
Rows whose recording URL appears more than once: 5,532

,user_id,recording_url,user_text
7,71949292,https://storage.googleapis.com/joshtalks-data-...,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...
11,72247256,https://storage.googleapis.com/joshtalks-data-...,"कुछ भी बना रहे हैं, अब तो गेम ही चल रही है, गे..."
12,73147059,https://storage.googleapis.com/joshtalks-data-...,कोई चीज रह गई हो या आपसे कोई सब्जी जल गई हो
27,74391133,https://storage.googleapis.com/joshtalks-data-...,हमने सुना है कि बालाजी मंदिर में आप जो समान ले...
43,74448617,https://storage.googleapis.com/joshtalks-data-...,कोई कड़ी टूट ही जाता था पता नहीं चल पाता था क...
52,74636332,https://storage.googleapis.com/joshtalks-data-...,ताकि हम सामने वाले को अगली बार हसने का मौका ही...
53,74637131,https://storage.googleapis.com/joshtalks-data-...,हाँ सर्दीयां तो आते ही पतंगबाजी शुरू हो जाती ह...
68,74829703,https://storage.googleapis.com/joshtalks-data-...,"और कॉलेज में यह भी होता है हां, कॉलेज में कि आ..."
77,74840332,https://storage.googleapis.com/joshtalks-data-...,हां वो दोनों के साइड से यही हो रहा है आपकी भी ...
87,74873229,https://storage.googleapis.com/joshtalks-data-...,मतलब सौ रीज़न होते हैं एक इंसान के ऊपर दबाव के ...

In [1]:

import numpy as np
import pandas as pd

numeric_columns = [
    "duration",
    "time_taken_by_user",
    "segment_character_per_second"
]

for column in numeric_columns:
    values = pd.to_numeric(df_raw[column], errors="coerce")

    print(f"\n--- {column} ---")
    print("Missing or non-numeric:", values.isna().sum())
    print("Zero values:", (values == 0).sum())
    print("Negative values:", (values < 0).sum())
    print("Positive infinity:", np.isposinf(values).sum())
    print("Negative infinity:", np.isneginf(values).sum())

    display(values.describe().to_frame("statistics"))

NameError: name 'df_raw' is not defined

In [2]:

import numpy as np
import pandas as pd

numeric_columns = [
    "duration",
    "time_taken_by_user",
    "segment_character_per_second"
]

for column in numeric_columns:
    values = pd.to_numeric(df_raw[column], errors="coerce")

    print(f"\n--- {column} ---")
    print("Missing values:", values.isna().sum())
    print("Zero values:", (values == 0).sum())
    print("Negative values:", (values < 0).sum())
    print("Infinite values:", np.isinf(values).sum())

    display(values.describe().to_frame("statistics"))

NameError: name 'df_raw' is not defined

In [3]:
import pandas as pd
import numpy as np
from pathlib import Path

data_candidates = [
    Path("data/raw/transcription_data.csv"),
    Path("../data/raw/transcription_data.csv"),
]
data_path = next((p for p in data_candidates if p.exists()), data_candidates[0])
df_raw = pd.read_csv(data_path)

FileNotFoundError: [Errno 2] No such file or directory: 'data\\raw\\transcription_data.csv'

In [4]:

import pandas as pd
import numpy as np
from pathlib import Path

# Find the project root from the notebook's working directory
current_dir = Path.cwd()

if current_dir.name == "notebooks":
    project_dir = current_dir.parent
else:
    project_dir = current_dir

data_path = project_dir / "data" / "raw" / "transcription_data.csv"

print("Working directory:", current_dir)
print("Dataset path:", data_path)
print("File exists:", data_path.exists())

df_raw = pd.read_csv(data_path)

print("Dataset loaded successfully!")
print("Shape:", df_raw.shape)
display(df_raw.head())

Working directory: c:\Users\mrdag\OneDrive\Desktop\josh-talks-q2\notebooks
Dataset path: c:\Users\mrdag\OneDrive\Desktop\josh-talks-q2\data\raw\transcription_data.csv
File exists: True
Dataset loaded successfully!
Shape: (51783, 8)

,user_id,recording_url,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second
0,71275781,https://storage.googleapis.com/joshtalks-data-...,इन जॉब में तो बहुत पैसे कमा है आपने,इन जॉब में तो बहुत पैसे कमा है आपने,No,2.94,15.00,9.18
1,71275800,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.96,14.26,3.13
2,71275813,https://storage.googleapis.com/joshtalks-data-...,तो उसमें एक मन एक मंत की सैल्वी उसमें आठ लिया...,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,Yes,4.83,20.85,7.87
3,71275842,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.45,8.46,6.67
4,71275856,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.27,11.65,11.11

In [5]:

numeric_columns = [
    "duration",
    "time_taken_by_user",
    "segment_character_per_second"
]

for column in numeric_columns:
    values = pd.to_numeric(df_raw[column], errors="coerce")

    print(f"\n--- {column} ---")
    print("Missing values:", values.isna().sum())
    print("Zero values:", (values == 0).sum())
    print("Negative values:", (values < 0).sum())
    print("Infinite values:", np.isinf(values).sum())

    display(values.describe().to_frame("statistics"))

--- duration ---
Missing values: 0
Zero values: 0
Negative values: 0
Infinite values: 0

         statistics
count  51783.000000
mean       5.476843
std        4.751795
min        0.030000
25%        0.900000
50%        4.000000
75%       10.080000
max       19.000000

--- time_taken_by_user ---
Missing values: 180
Zero values: 1
Negative values: 0
Infinite values: 0

         statistics
count  51603.000000
mean     159.589142
std     1390.558683
min        0.000000
25%        4.690000
50%       12.000000
75%       45.365000
max    72813.270000

--- segment_character_per_second ---
Missing values: 0
Zero values: 25
Negative values: 0
Infinite values: 0

         statistics
count  51783.000000
mean      12.001506
std       10.735695
min        0.000000
25%        6.900000
50%       10.370000
75%       12.920000
max      233.330000

In [6]:

# Columns that help us investigate each record
inspect_columns = [
    "user_id",
    "whisper_text",
    "user_text",
    "is_edited",
    "duration",
    "time_taken_by_user",
    "segment_character_per_second"
]

# 1. Ten longest user times
print("=== 10 LONGEST USER TIMES ===")
display(
    df_raw.nlargest(10, "time_taken_by_user")[inspect_columns]
)

# 2. Ten highest reported CPS values
print("=== 10 HIGHEST REPORTED CPS VALUES ===")
display(
    df_raw.nlargest(10, "segment_character_per_second")[inspect_columns]
)

# 3. Records with zero time taken
print("=== RECORDS WITH ZERO USER TIME ===")
display(
    df_raw.loc[df_raw["time_taken_by_user"] == 0, inspect_columns]
)

# 4. Records with zero reported CPS
print("=== RECORDS WITH ZERO REPORTED CPS ===")
display(
    df_raw.loc[
        df_raw["segment_character_per_second"] == 0,
        inspect_columns
    ].head(10)
)

=== 10 LONGEST USER TIMES ===

,user_id,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second
32954,75181729,"कुछ भी बना रहे हैं, अब तो गेम ही चल रही है, गे...","की चाहे कोछ भी बना रहे हैं, अब तो गेम ही चल रह...",Yes,10.00,72813.27,11.60
38121,73476889,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...,बहुत अ हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता...,Yes,19.00,53647.11,11.16
43479,73389697,उसमें का एक ग्रुप बन गया है अब कुछ दोस्तों का ...,उसमें का एक ग्रुप बन गया है अब कुछ दोस्तों का ...,Yes,7.00,51921.43,16.00
30069,73146541,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...,बहुत हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता ज...,Yes,19.00,47876.04,10.47
26770,74982783,"कुछ भी बना रहे हैं, अब तो गेम ही चल रही है, गे...","कि.. चाहे कुछ भी बना रहे हैं, अब तो गेम ही चल ...",Yes,10.00,47779.18,11.90
20476,73162156,अच्छा तो ये राजस्थान का फेमस खाना है तो आपको क...,जी जी अच्छा तो ये राजस्थान का फेमस खाना है तो ...,Yes,7.00,47019.67,15.43
48149,73081067,जो टेनिस की बॉल होती थी थोड़ी सी टेनिस वाली बॉ...,अच्छा वह जो टेनिस की बॉल होती थी थोड़ी सी टेनि...,Yes,8.00,45661.58,14.00
44036,72932943,चीज रह गई हो या आपसे कोई,कोई चीज रह गई हो या आपसे कोई चिज़ जल गई हो,Yes,3.00,41639.11,10.33
19456,71415490,अच्छा मतलब किसी फ्रेंड का अपना मतलब सोचा था ब...,अच्छा मतलब किसी फ्रेंड का अपना मतलब सोचा था बट...,Yes,4.08,40911.53,12.75
24947,60337281,NaN,तो क्या है। जहां पे बेड़ होती है। उसकी तरफ जाक...,Yes,12.81,40711.60,13.82

=== 10 HIGHEST REPORTED CPS VALUES ===

,user_id,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second
26532,72268139,NaN,[blank],Yes,0.03,4.50,233.33
36760,72033578,NaN,[blank],Yes,0.03,12.39,233.33
6354,71482865,प्रति प्रति प्रति प्रति प्रति प्रति प्रति प्र...,प्रति प्रति प्रति प्रति प्रति प्रति प्रति प्र...,No,1.05,15.73,177.14
14945,72187111,प्रति प्रति प्रति प्रति प्रति प्रति प्रति प्र...,प्रति प्रति प्रति प्रति प्रति प्रति प्रति प्र...,No,1.17,1.68,158.97
36010,73402512,पुराण पर पुराण पर पुराण पर पुराण पर पुराण पर ...,पुराण पर पुराण पर पुराण पर पुराण पर पुराण पर ...,Yes,1.11,20.57,137.84
8025,71892761,NaN,कोई आवाज नहीं आ रही,Yes,0.12,15.15,125.00
50743,580062,NaN,",,,,,,,,,,,,,,",Yes,0.12,5.00,116.67
22395,73855398,NaN,No voice blank,Yes,0.12,6.94,100.00
49760,222099,NaN,थक..........,Yes,0.12,10.00,100.00
13423,72848010,NaN,ब्लैंक ऑडियो,Yes,0.12,8.11,91.67

=== RECORDS WITH ZERO USER TIME ===

,user_id,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second
5218,73653653,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...,बहुत हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता ज...,Yes,19.0,0.0,11.58

=== RECORDS WITH ZERO REPORTED CPS ===

,user_id,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second
6234,73419392,पेशास में भी कावश्यकती लगती है,,Yes,2.79,91.53,0.0
6272,73630824,NaN,,Yes,0.33,7.77,0.0
6318,73853021,अब यूज़ नहीं पाता है कि अब यूज़ में जगा रहा है।,,Yes,5.91,174.23,0.0
11741,60382675,NaN,,Yes,12.69,27.66,0.0
11743,60373023,NaN,,Yes,2.07,34.65,0.0
11755,71353225,NaN,,Yes,0.33,9.22,0.0
11765,71415820,NaN,,Yes,0.18,239.27,0.0
11770,71485152,NaN,,Yes,1.02,18.76,0.0
11777,71484579,NaN,,Yes,0.24,9.64,0.0
11778,71484639,NaN,,Yes,0.57,10.58,0.0

In [7]:

# Work on a copy; preserve the original dataset
df = df_raw.copy()

# Count characters, excluding ordinary spaces
text = df["user_text"].fillna("").astype(str)
df["char_count"] = text.str.replace(" ", "", regex=False).str.len()

# Separate count excluding the exact [blank] marker
df["char_count_excluding_blank_marker"] = (
    text.where(text.str.strip().ne("[blank]"), "")
        .str.replace(" ", "", regex=False)
        .str.len()
)

# Calculate user transcription speed
# Invalid or missing task times produce NaN, not infinity
valid_time = df["time_taken_by_user"].where(
    df["time_taken_by_user"] > 0
)

df["user_task_cps"] = df["char_count"] / valid_time

print("Original rows and columns:", df_raw.shape)
print("New rows and columns:", df.shape)
display(df[[
    "user_text",
    "char_count",
    "char_count_excluding_blank_marker",
    "time_taken_by_user",
    "user_task_cps"
]].head(10))

Original rows and columns: (51783, 8)
New rows and columns: (51783, 11)

,user_text,char_count,char_count_excluding_blank_marker,time_taken_by_user,user_task_cps
0,इन जॉब में तो बहुत पैसे कमा है आपने,27,27,15.00,1.800000
1,हूं,3,3,14.26,0.210379
2,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,38,38,20.85,1.822542
3,हूं,3,3,8.46,0.354610
4,हूं,3,3,11.65,0.257511
5,पर विगराम कोई ने कोई मिल जाता है दिरीदर दोस्त...,96,96,24.25,3.958763
6,हां बिल्कुल क्योंकि रिश्तेदार तो हो सकते हैं द...,70,70,48.44,1.445087
7,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...,176,176,75.64,2.326811
8,"आपकी आवाज क्लियर नहीं आ रही है। हाँ, अभी आईए।...",49,49,14.33,3.419400
9,हेलो आ रही है आ रही है कम कम आ रही है थोड़ी क...,124,124,16.90,7.337278

In [9]:

text = df["user_text"].fillna("").astype(str).str.strip()

print("Missing user_text:", df["user_text"].isna().sum())
print("Empty or whitespace-only text:", text.eq("").sum())
print("Exact [blank] marker:", text.eq("[blank]").sum())
print("Missing task time:", df["time_taken_by_user"].isna().sum())
print("Zero task time:", df["time_taken_by_user"].eq(0).sum())
print("Missing user_task_cps:", df["user_task_cps"].isna().sum())

print("\nExamples of [blank] records:")
display(
    df.loc[
        text.eq("[blank]"),
        ["user_text", "duration", "time_taken_by_user",
         "char_count", "char_count_excluding_blank_marker",
         "user_task_cps"]
    ].head(5)
)

Missing user_text: 0
Empty or whitespace-only text: 26
Exact [blank] marker: 9748
Missing task time: 180
Zero task time: 1
Missing user_task_cps: 181

Examples of [blank] records:

,user_text,duration,time_taken_by_user,char_count,char_count_excluding_blank_marker,user_task_cps
10,[blank],0.15,293.61,7,0,0.023841
19,[blank],0.15,7.43,7,0,0.942127
29,[blank],0.24,27.40,7,0,0.255474
33,[blank],0.21,5.05,7,0,1.386139
44,[blank],0.33,4.03,7,0,1.736973

In [13]:

# Work on the existing copy; preserve df_raw
text = df["user_text"].fillna("").astype(str).str.strip()

# Count characters, excluding whitespace and the exact [blank] marker
df["analysis_char_count"] = (
    text.where(text.ne("[blank]"), "")
        .str.replace(r"\s+", "", regex=True)
        .str.len()
)

# Calculate user transcription speed
valid_time = df["time_taken_by_user"].where(
    df["time_taken_by_user"] > 0
)

df["user_task_cps"] = df["analysis_char_count"] / valid_time

print("Total records:", len(df))
print("Missing user_task_cps:", df["user_task_cps"].isna().sum())

display(df_raw.head())

Total records: 51783
Missing user_task_cps: 181

,user_id,recording_url,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second
0,71275781,https://storage.googleapis.com/joshtalks-data-...,इन जॉब में तो बहुत पैसे कमा है आपने,इन जॉब में तो बहुत पैसे कमा है आपने,No,2.94,15.00,9.18
1,71275800,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.96,14.26,3.13
2,71275813,https://storage.googleapis.com/joshtalks-data-...,तो उसमें एक मन एक मंत की सैल्वी उसमें आठ लिया...,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,Yes,4.83,20.85,7.87
3,71275842,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.45,8.46,6.67
4,71275856,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.27,11.65,11.11

In [14]:

columns_to_display = [
    "user_id",
    "recording_url",
    "whisper_text",
    "user_text",
    "is_edited",
    "duration",
    "time_taken_by_user",
    "segment_character_per_second",
    "char_count",
    "char_count_excluding_blank_marker",
    "analysis_char_count",
    "user_task_cps"
]

display(df[columns_to_display].head(10))

,user_id,recording_url,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second,char_count,char_count_excluding_blank_marker,analysis_char_count,user_task_cps
0,71275781,https://storage.googleapis.com/joshtalks-data-...,इन जॉब में तो बहुत पैसे कमा है आपने,इन जॉब में तो बहुत पैसे कमा है आपने,No,2.94,15.00,9.18,27,27,27,1.800000
1,71275800,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.96,14.26,3.13,3,3,3,0.210379
2,71275813,https://storage.googleapis.com/joshtalks-data-...,तो उसमें एक मन एक मंत की सैल्वी उसमें आठ लिया...,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,Yes,4.83,20.85,7.87,38,38,38,1.822542
3,71275842,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.45,8.46,6.67,3,3,3,0.354610
4,71275856,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.27,11.65,11.11,3,3,3,0.257511
5,71274726,https://storage.googleapis.com/joshtalks-data-...,पर विगराम कोई ने कोई मिल जाता है दिरीदर दोस्त...,पर विगराम कोई ने कोई मिल जाता है दिरीदर दोस्त...,No,8.43,24.25,11.39,96,96,96,3.958763
6,71274776,https://storage.googleapis.com/joshtalks-data-...,आप बिल्कुल क्योंकि वरिषिदार तो हो सकते हैं दू...,हां बिल्कुल क्योंकि रिश्तेदार तो हो सकते हैं द...,Yes,5.97,48.44,11.73,70,70,70,1.445087
7,71949292,https://storage.googleapis.com/joshtalks-data-...,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...,Yes,19.00,75.64,9.26,176,176,176,2.326811
8,71285483,https://storage.googleapis.com/joshtalks-data-...,"आपकी आवाज क्लियर नहीं आ रही है। हाँ, अभी आईए।...","आपकी आवाज क्लियर नहीं आ रही है। हाँ, अभी आईए।...",No,9.48,14.33,5.17,49,49,49,3.419400
9,71285500,https://storage.googleapis.com/joshtalks-data-...,हेलो आ रही है आ रही है कम कम आ रही है थोड़ी क...,हेलो आ रही है आ रही है कम कम आ रही है थोड़ी क...,No,9.81,16.90,12.64,124,124,124,7.337278

In [15]:
# Step 0A: Inspect the current dataframe
print("Dataset shape:", df.shape)

print("\nExisting columns:")
print(df.columns.tolist())

print("\nData types and non-null counts:")
df.info()

Dataset shape: (51783, 12)

Existing columns:
['user_id', 'recording_url', 'whisper_text', 'user_text', 'is_edited', 'duration', 'time_taken_by_user', 'segment_character_per_second', 'char_count', 'char_count_excluding_blank_marker', 'user_task_cps', 'analysis_char_count']

Data types and non-null counts:
<class 'pandas.DataFrame'>
RangeIndex: 51783 entries, 0 to 51782
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   user_id                            51783 non-null  int64
 1   recording_url                      51783 non-null  str
 2   whisper_text                       28681 non-null  str
 3   user_text                          51783 non-null  str
 4   is_edited                          51783 non-null  str
 5   duration                           51783 non-null  float64
 6   time_taken_by_user                 51603 non-null  float64
 7   segment_character_per_second       51783 non-null  float64
 8   char_count                         51783 non-null  int64
 9   char_count_excluding_blank_marker  51783 non-null  int64
 10  user_task_cps                      51602 non-null  float64
 11  analysis_char_count                51783 non-null  int64
dtypes: float64(4), int64(4), str(4)
memory usage: 4.7 MB

In [16]:
# Step 0D: Validate existing analysis columns

print("Edit status values:")
display(df["is_edited"].value_counts(dropna=False))

print("\nMissing values:")
display(df[
    [
        "duration",
        "time_taken_by_user",
        "analysis_char_count",
        "user_task_cps"
    ]
].isna().sum().rename("missing_count"))

print("\nDuration and task-time validity:")
print("Non-positive durations:", (df["duration"] <= 0).sum())
print("Non-positive task times:", (df["time_taken_by_user"] <= 0).sum())

print("\nCheck existing character-count columns:")
display(
    df[
        [
            "user_text",
            "char_count",
            "char_count_excluding_blank_marker",
            "analysis_char_count",
            "user_task_cps"
        ]
    ].head(10)
)

Edit status values:

is_edited
Yes    43192
No      8591
Name: count, dtype: int64

Missing values:

duration                 0
time_taken_by_user     180
analysis_char_count      0
user_task_cps          181
Name: missing_count, dtype: int64

Duration and task-time validity:
Non-positive durations: 0
Non-positive task times: 1

Check existing character-count columns:

,user_text,char_count,char_count_excluding_blank_marker,analysis_char_count,user_task_cps
0,इन जॉब में तो बहुत पैसे कमा है आपने,27,27,27,1.800000
1,हूं,3,3,3,0.210379
2,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,38,38,38,1.822542
3,हूं,3,3,3,0.354610
4,हूं,3,3,3,0.257511
5,पर विगराम कोई ने कोई मिल जाता है दिरीदर दोस्त...,96,96,96,3.958763
6,हां बिल्कुल क्योंकि रिश्तेदार तो हो सकते हैं द...,70,70,70,1.445087
7,हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही ...,176,176,176,2.326811
8,"आपकी आवाज क्लियर नहीं आ रही है। हाँ, अभी आईए।...",49,49,49,3.419400
9,हेलो आ रही है आ रही है कम कम आ रही है थोड़ी क...,124,124,124,7.337278

In [17]:
# Step 0E: Create clean prerequisite columns without overwriting originals

df["duration_clean"] = pd.to_numeric(df["duration"], errors="coerce")
df["task_time_clean"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

df["edit_status_clean"] = (
    df["is_edited"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({"yes": True, "no": False})
)

# Verify whether the existing character count matches our analysis definition
text = df["user_text"].fillna("").astype(str).str.strip()

expected_char_count = (
    text.where(text.ne("[blank]"), "")
    .str.replace(r"\s+", "", regex=True)
    .str.len()
)

print(
    "Rows where analysis_char_count differs:",
    (df["analysis_char_count"] != expected_char_count).sum()
)

print(
    "Rows where existing CPS differs from recalculated CPS:",
    (
        ~np.isclose(
            df["user_task_cps"],
            expected_char_count / df["task_time_clean"].where(
                df["task_time_clean"] > 0
            ),
            equal_nan=True
        )
    ).sum()
)

print("\nUnrecognized edit statuses:", df["edit_status_clean"].isna().sum())
print("Invalid durations:", (df["duration_clean"] <= 0).sum())
print(
    "Missing or non-positive task times:",
    (
        df["task_time_clean"].isna()
        | (df["task_time_clean"] <= 0)
    ).sum()
)

Rows where analysis_char_count differs: 0
Rows where existing CPS differs from recalculated CPS: 0

Unrecognized edit statuses: 0
Invalid durations: 0
Missing or non-positive task times: 181

In [18]:
# Step 1A: Calculate TER warning indicators

df["ter"] = (
    df["task_time_clean"] / df["duration_clean"]
)

df["flag_ter_below_1"] = (
    (df["ter"] < 1) &
    (df["duration_clean"] >= 2)
)

df["flag_ter_above_50"] = df["ter"] > 50

df["flag_task_time_above_1h"] = (
    df["task_time_clean"] > 3600
)

ter_flags = pd.Series({
    "TER < 1 and audio >= 2 seconds":
        df["flag_ter_below_1"].sum(),
    "TER > 50":
        df["flag_ter_above_50"].sum(),
    "Task time > 1 hour":
        df["flag_task_time_above_1h"].sum()
}, name="flagged_tasks")

display(ter_flags.to_frame())

                                flagged_tasks
TER < 1 and audio >= 2 seconds           5806
TER > 50                                 2611
Task time > 1 hour                        433

In [19]:
# Step 1B: Inspect task volume per user

user_task_counts = df.groupby("user_id").size()

print("Total unique users:", df["user_id"].nunique())
print("Median tasks per user:", user_task_counts.median())
print("Users with at least 20 tasks:", (user_task_counts >= 20).sum())
print("Users with at least 50 tasks:", (user_task_counts >= 50).sum())

display(
    user_task_counts.describe(
        percentiles=[0.25, 0.50, 0.75, 0.90, 0.95]
    ).to_frame(name="tasks_per_user")
)

Total unique users: 48875
Median tasks per user: 1.0
Users with at least 20 tasks: 10
Users with at least 50 tasks: 10

       tasks_per_user
count    48875.000000
mean         1.059499
std          4.758073
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
90%          1.000000
95%          1.000000
max        609.000000

In [20]:
# Step 1C: Calculate per-user edit rates

user_edit_summary = (
    df.groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        edited_tasks=("edit_status_clean", "sum"),
        unedited_tasks=("edit_status_clean", lambda x: (~x).sum())
    )
    .reset_index()
)

user_edit_summary["edit_rate"] = (
    user_edit_summary["edited_tasks"]
    / user_edit_summary["total_tasks"]
)

# Only assess users with sufficient task history
user_edit_summary["eligible_20_tasks"] = (
    user_edit_summary["total_tasks"] >= 20
)

user_edit_summary["eligible_50_tasks"] = (
    user_edit_summary["total_tasks"] >= 50
)

print("Users with >=20 tasks:", user_edit_summary["eligible_20_tasks"].sum())
print("Users with >=50 tasks:", user_edit_summary["eligible_50_tasks"].sum())

print("\nUsers with >=20 tasks and edit rate <30%:")
print(
    (
        user_edit_summary["eligible_20_tasks"]
        & (user_edit_summary["edit_rate"] < 0.30)
    ).sum()
)

print("\nUsers with >=50 tasks and edit rate <15%:")
print(
    (
        user_edit_summary["eligible_50_tasks"]
        & (user_edit_summary["edit_rate"] < 0.15)
    ).sum()
)

display(
    user_edit_summary
    .sort_values("total_tasks", ascending=False)
    .head(10)
)

Users with >=20 tasks: 10
Users with >=50 tasks: 10

Users with >=20 tasks and edit rate <30%:
0

Users with >=50 tasks and edit rate <15%:
0

,user_id,total_tasks,edited_tasks,unedited_tasks,edit_rate,eligible_20_tasks,eligible_50_tasks
6,580062,609,531,78,0.871921,True,True
3,393886,509,493,16,0.968566,True,True
8,681509,358,355,3,0.991620,True,True
4,410566,349,320,29,0.916905,True,True
0,222099,333,329,4,0.987988,True,True
1,311760,184,184,0,1.000000,True,True
5,467270,176,171,5,0.971591,True,True
7,632098,165,95,70,0.575758,True,True
2,326611,149,149,0,1.000000,True,True
9,688393,86,72,14,0.837209,True,True

In [21]:
# Step 1: Derive candidate thresholds from observed data

metrics = {
    "TER": df["ter"],
    "Task time (seconds)": df["task_time_clean"],
    "User-task CPS": df["user_task_cps"]
}

threshold_results = []

for name, series in metrics.items():
    x = series.replace([np.inf, -np.inf], np.nan).dropna()

    q01 = x.quantile(0.01)
    q05 = x.quantile(0.05)
    q25 = x.quantile(0.25)
    q50 = x.quantile(0.50)
    q75 = x.quantile(0.75)
    q95 = x.quantile(0.95)
    q99 = x.quantile(0.99)

    iqr = q75 - q25
    lower_fence = max(0, q25 - 1.5 * iqr)
    upper_fence = q75 + 1.5 * iqr

    threshold_results.append({
        "metric": name,
        "valid_tasks": len(x),
        "p01": q01,
        "p05": q05,
        "p25": q25,
        "median": q50,
        "p75": q75,
        "p95": q95,
        "p99": q99,
        "IQR_lower_fence": lower_fence,
        "IQR_upper_fence": upper_fence,
        "below_lower_fence": (x < lower_fence).sum(),
        "above_upper_fence": (x > upper_fence).sum()
    })

threshold_table = pd.DataFrame(threshold_results).set_index("metric")
display(threshold_table.round(3))

# Edit-rate distribution among users with sufficient task history
eligible_users = user_edit_summary.loc[
    user_edit_summary["total_tasks"] >= 20
].copy()

print("\nEligible users for edit-rate analysis:", len(eligible_users))

if len(eligible_users) > 0:
    display(
        eligible_users["edit_rate"]
        .describe(percentiles=[0.10, 0.25, 0.50, 0.75, 0.90])
        .to_frame("edit_rate")
        .round(3)
    )

,valid_tasks,p01,p05,p25,median,p75,p95,p99,IQR_lower_fence,IQR_upper_fence,below_lower_fence,above_upper_fence
metric,,,,,,,,,,,,
TER,51603,0.179,0.401,2.318,6.273,13.580,50.800,685.312,0,30.474,0,4454
Task time (seconds),51603,1.390,1.880,4.690,12.000,45.365,243.105,2734.139,0,106.378,0,6310
User-task CPS,51602,0.000,0.000,0.232,0.885,2.675,19.725,57.085,0,6.340,0,6893

Eligible users for edit-rate analysis: 10

       edit_rate
count     10.000
mean       0.912
std        0.131
min        0.576
10%        0.811
25%        0.883
50%        0.970
75%        0.991
90%        1.000
max        1.000

In [22]:
# Step 2: Compare CPS thresholds and inspect flagged examples

valid_cps = df.loc[
    (df["duration_clean"] > 5) &
    df["user_task_cps"].notna()
].copy()

candidate_thresholds = [
    valid_cps["user_task_cps"].quantile(0.95),
    valid_cps["user_task_cps"].quantile(0.99),
    valid_cps["user_task_cps"].quantile(0.995),
    valid_cps["user_task_cps"].quantile(0.999)
]

cps_threshold_table = pd.DataFrame({
    "threshold": candidate_thresholds
})

cps_threshold_table["flagged_tasks"] = [
    (valid_cps["user_task_cps"] > threshold).sum()
    for threshold in candidate_thresholds
]

cps_threshold_table["percentage"] = (
    100 * cps_threshold_table["flagged_tasks"] / len(valid_cps)
)

display(cps_threshold_table.round(3))

print("\nHighest CPS examples (audio duration > 5 seconds):")

display(
    valid_cps.nlargest(15, "user_task_cps")[
        [
            "user_id",
            "duration_clean",
            "task_time_clean",
            "analysis_char_count",
            "user_task_cps",
            "user_text"
        ]
    ]
)

   threshold  flagged_tasks  percentage
0     39.028           1142       5.001
1     71.844            229       1.003
2     80.802            115       0.504
3    100.747             23       0.101

Highest CPS examples (audio duration > 5 seconds):

,user_id,duration_clean,task_time_clean,analysis_char_count,user_task_cps,user_text
15395,72663482,6.69,1.58,186,117.721519,प्रति प्रति प्रति प्रति प्रति प्रति प्रति प्र...
14776,71968177,13.17,1.47,172,117.006803,तो हम अगर जैसे कि केरल में शायद आई थिंक इडली ...
15797,72854296,14.49,1.47,172,117.006803,जी बिल्डोर और यह चीजें हैं ना कि जैसे अलग-अलग...
15060,72467024,13.38,1.58,184,116.455696,सिर्फ बैठकर observe करना मुझे कैसा लग रहा है ...
15783,72853318,11.85,1.59,184,115.723270,सब्सक्राइब करें हैं इसलिए और एक दोिन ऐसी जाता...
15639,72760893,13.83,1.46,168,115.068493,पहले क्या होता था मनी ओडर चलता था बैंक ट्रांस...
42791,71479110,13.68,1.54,177,114.935065,"नहीं, मैं मतादाता हूँ, मेरी बात सुनो। इसमें ऐ..."
15499,72579794,13.62,1.56,174,111.538462,तो बात रही पारंपरी कहां कपड़ों की तो कपड़े तो...
15495,72574749,12.75,1.50,167,111.333333,और आज की समय में देखते हुए बच्चे इतना बोज तो ...
15775,72853163,11.85,1.50,167,111.333333,क्या उनकी क्वेश्चन नहीं है ? नहीं यह न गाइड व...
15221,72573447,14.43,1.54,168,109.090909,लड़कियों का समान काफी ज्यादा समान होता है लड़...
14499,71044053,13.08,1.80,196,108.888889,जैसे बहुत सारी बिमारियां हैं जो कि हम अपने pa...
15467,72271202,12.03,1.49,160,107.382550,बताया है हम उसको पीछे धखेलते थोड़ी हैं उसको आ...
42738,71422444,12.21,1.60,171,106.875000,पुराना दुकान था तो उसको मम्मी ने सोचा कि हम र...
43223,72567977,11.76,1.54,164,106.493506,तो उन्हें सरम नहीं है बड़े लोग थोड़ा जाएंगे च...

In [23]:
# Recalculate CPS thresholds on tasks with audio duration > 5 seconds

valid_cps = df.loc[
    (df["duration_clean"] > 5)
    & df["user_task_cps"].notna()
].copy()

percentiles = [0.95, 0.99, 0.995, 0.999]

rows = []

for p in percentiles:
    threshold = valid_cps["user_task_cps"].quantile(p)
    count = (valid_cps["user_task_cps"] > threshold).sum()

    rows.append({
        "percentile": f"{p:.1%}",
        "threshold_cps": threshold,
        "flagged_tasks": count,
        "percentage_of_eligible_tasks": 100 * count / len(valid_cps)
    })

display(pd.DataFrame(rows).round(3))

# Check whether high-CPS tasks have task time shorter than audio duration
high_cps = valid_cps[
    valid_cps["user_task_cps"] > valid_cps["user_task_cps"].quantile(0.99)
].copy()

high_cps["task_time_shorter_than_audio"] = (
    high_cps["task_time_clean"] < high_cps["duration_clean"]
)

print("Top 1% CPS tasks:", len(high_cps))
print(
    "Top 1% with task time shorter than audio:",
    high_cps["task_time_shorter_than_audio"].sum()
)

display(
    high_cps[
        [
            "duration_clean",
            "task_time_clean",
            "analysis_char_count",
            "user_task_cps",
            "task_time_shorter_than_audio"
        ]
    ].head(10)
)

  percentile  threshold_cps  flagged_tasks  percentage_of_eligible_tasks
0      95.0%         39.028           1142                         5.001
1      99.0%         71.844            229                         1.003
2      99.5%         80.802            115                         0.504
3      99.9%        100.747             23                         0.101

Top 1% CPS tasks: 229
Top 1% with task time shorter than audio: 229

,duration_clean,task_time_clean,analysis_char_count,user_task_cps,task_time_shorter_than_audio
14499,13.08,1.80,196,108.888889,True
14525,11.88,1.86,141,75.806452,True
14547,12.90,1.82,135,74.175824,True
14556,10.95,1.82,131,71.978022,True
14560,14.16,1.90,166,87.368421,True
14583,14.28,1.80,172,95.555556,True
14604,14.01,1.73,151,87.283237,True
14668,11.10,1.69,131,77.514793,True
14678,13.62,2.04,180,88.235294,True
14687,12.60,1.75,129,73.714286,True

In [24]:
# Step 3: Clean CPS threshold comparison and overlap with TER warnings

valid_cps = df.loc[
    (df["duration_clean"] > 5) &
    df["user_task_cps"].notna()
].copy()

thresholds = {
    "P95": valid_cps["user_task_cps"].quantile(0.95),
    "P99": valid_cps["user_task_cps"].quantile(0.99),
    "P99.5": valid_cps["user_task_cps"].quantile(0.995),
    "P99.9": valid_cps["user_task_cps"].quantile(0.999)
}

rows = []

for label, threshold in thresholds.items():
    cps_flag = valid_cps["user_task_cps"] > threshold
    ter_flag = valid_cps["flag_ter_below_1"]

    rows.append({
        "percentile": label,
        "threshold_cps": threshold,
        "cps_flagged": int(cps_flag.sum()),
        "also_TER_below_1": int((cps_flag & ter_flag).sum()),
        "CPS_flags_with_TER_below_1_pct": (
            100 * (cps_flag & ter_flag).sum() / cps_flag.sum()
            if cps_flag.sum() else 0
        )
    })

display(pd.DataFrame(rows).round(3))

,percentile,threshold_cps,cps_flagged,also_TER_below_1,CPS_flags_with_TER_below_1_pct
0,P95,39.028,1142,1142,100.0
1,P99,71.844,229,229,100.0
2,P99.5,80.802,115,115,100.0
3,P99.9,100.747,23,23,100.0

In [25]:
# Step 4: Consolidate task-level warning signals

df["warning_timing"] = (
    df["flag_ter_below_1"] |
    df["flag_ter_above_50"] |
    df["flag_task_time_above_1h"]
)

df["warning_cps_support"] = (
    (df["duration_clean"] > 5) &
    (df["user_task_cps"] > valid_cps["user_task_cps"].quantile(0.99))
)

df["warning_count_primary"] = (
    df["flag_ter_below_1"].astype(int) +
    df["flag_ter_above_50"].astype(int) +
    df["flag_task_time_above_1h"].astype(int)
)

summary = pd.Series({
    "Tasks with any timing warning": df["warning_timing"].sum(),
    "Tasks with high-CPS supporting signal": df["warning_cps_support"].sum(),
    "Tasks with multiple timing flags": (
        df["warning_count_primary"] > 1
    ).sum()
}, name="task_count")

display(summary.to_frame())

                                       task_count
Tasks with any timing warning                8417
Tasks with high-CPS supporting signal         229
Tasks with multiple timing flags              433

In [26]:
# Step 5: Inspect overlap between timing warning rules

timing_overlap = pd.crosstab(
    df["flag_ter_below_1"],
    df["flag_ter_above_50"],
    rownames=["TER < 1"],
    colnames=["TER > 50"]
)

display(timing_overlap)

print("\nOverlap with task time > 1 hour:")
display(
    pd.crosstab(
        df["flag_ter_above_50"],
        df["flag_task_time_above_1h"],
        rownames=["TER > 50"],
        colnames=["Task time > 1 hour"]
    )
)

print("\nSample timing-warning records:")
display(
    df.loc[
        df["warning_timing"],
        [
            "user_id",
            "duration_clean",
            "task_time_clean",
            "ter",
            "analysis_char_count",
            "user_task_cps",
            "flag_ter_below_1",
            "flag_ter_above_50",
            "flag_task_time_above_1h"
        ]
    ].head(10)
)

TER > 50  False  True
TER < 1
False     43366   2611
True       5806      0

Overlap with task time > 1 hour:

Task time > 1 hour  False  True
TER > 50
False               49172      0
True                 2178    433

Sample timing-warning records:

,user_id,duration_clean,task_time_clean,ter,analysis_char_count,user_task_cps,flag_ter_below_1,flag_ter_above_50,flag_task_time_above_1h
10,71274541,0.15,293.61,1957.400000,0,0.000000,False,True,False
11,72247256,10.00,7221.75,722.175000,106,0.014678,False,True,True
12,73147059,3.00,17565.67,5855.223333,32,0.001822,False,True,True
20,71544250,0.42,43.99,104.738095,3,0.068197,False,True,False
21,72038889,6.18,10485.61,1696.700647,3,0.000286,False,True,True
27,74391133,5.00,9282.83,1856.566000,62,0.006679,False,True,True
29,72666524,0.24,27.40,114.166667,0,0.000000,False,True,False
31,72276398,11.85,2109.03,177.977215,150,0.071123,False,True,False
36,72750587,0.24,12.91,53.791667,3,0.232378,False,True,False
48,72749745,0.12,2734.31,22785.916667,0,0.000000,False,True,False

In [28]:
# PART 1: Final warning-signal rules and summary

# 1. Derive thresholds from the observed dataset
valid_ter = df["ter"].replace([np.inf, -np.inf], np.nan).dropna()
valid_cps = df.loc[
    (df["duration_clean"] > 5) & df["user_task_cps"].notna(),
    "user_task_cps"
].replace([np.inf, -np.inf], np.nan).dropna()

ter_p95 = valid_ter.quantile(0.95)
ter_p99 = valid_ter.quantile(0.99)
cps_p99 = valid_cps.quantile(0.99)

# 2. Primary timing warning: task time shorter than audio
df["final_flag_shorter_than_audio"] = (
    (df["ter"] < 1) & (df["duration_clean"] >= 2)
)

# 3. Extreme TER warning: top 1% of observed TER
df["final_flag_extreme_ter"] = df["ter"] > ter_p99

# 4. CPS supporting diagnostic: top 1% for audio > 5 seconds
df["final_flag_extreme_cps"] = (
    (df["duration_clean"] > 5) &
    (df["user_task_cps"] > cps_p99)
)

# 5. Consolidated task-level review flag
df["final_flag_for_review"] = (
    df["final_flag_shorter_than_audio"] |
    df["final_flag_extreme_ter"]
)

# 6. Summarize thresholds and counts
final_summary = pd.DataFrame([
    {
        "signal": "TER < 1; audio >= 2 sec",
        "threshold": 1,
        "flagged_tasks": int(df["final_flag_shorter_than_audio"].sum())
    },
    {
        "signal": "TER above P99",
        "threshold": ter_p99,
        "flagged_tasks": int(df["final_flag_extreme_ter"].sum())
    },
    {
        "signal": "CPS above P99; audio > 5 sec",
        "threshold": cps_p99,
        "flagged_tasks": int(df["final_flag_extreme_cps"].sum())
    },
    {
        "signal": "Any primary warning",
        "threshold": np.nan,
        "flagged_tasks": int(df["final_flag_for_review"].sum())
    }
])

final_summary["percentage_of_all_tasks"] = (
    100 * final_summary["flagged_tasks"] / len(df)
)

print("TER P95:", round(ter_p95, 3))
print("TER P99:", round(ter_p99, 3))
print("CPS P99 (audio > 5 sec):", round(cps_p99, 3))

display(final_summary.round(3))

# 7. Edit-rate assessment: report evidence, don't force a threshold
eligible_users = user_edit_summary.loc[
    user_edit_summary["total_tasks"] >= 20
].copy()

print("\nEDIT-RATE ASSESSMENT")
print("Users with >=20 tasks:", len(eligible_users))
print(
    "Eligible users with edit rate <30%:",
    (eligible_users["edit_rate"] < 0.30).sum()
)
print(
    "Eligible users with edit rate <15%:",
    (eligible_users["edit_rate"] < 0.15).sum()
)

# 8. Save no files and change no original data; show sample flagged tasks
display(
    df.loc[
        df["final_flag_for_review"],
        [
            "user_id",
            "duration_clean",
            "task_time_clean",
            "ter",
            "analysis_char_count",
            "user_task_cps",
            "final_flag_shorter_than_audio",
            "final_flag_extreme_ter",
            "final_flag_extreme_cps"
        ]
    ].head(10)
)

TER P95: 50.8
TER P99: 685.312
CPS P99 (audio > 5 sec): 71.844

,signal,threshold,flagged_tasks,percentage_of_all_tasks
0,TER < 1; audio >= 2 sec,1.000,5806,11.212
1,TER above P99,685.312,517,0.998
2,CPS above P99; audio > 5 sec,71.844,229,0.442
3,Any primary warning,NaN,6323,12.211

EDIT-RATE ASSESSMENT
Users with >=20 tasks: 10
Eligible users with edit rate <30%: 0
Eligible users with edit rate <15%: 0

,user_id,duration_clean,task_time_clean,ter,analysis_char_count,user_task_cps,final_flag_shorter_than_audio,final_flag_extreme_ter,final_flag_extreme_cps
10,71274541,0.15,293.61,1957.400000,0,0.000000,False,True,False
11,72247256,10.00,7221.75,722.175000,106,0.014678,False,True,False
12,73147059,3.00,17565.67,5855.223333,32,0.001822,False,True,False
21,72038889,6.18,10485.61,1696.700647,3,0.000286,False,True,False
27,74391133,5.00,9282.83,1856.566000,62,0.006679,False,True,False
48,72749745,0.12,2734.31,22785.916667,0,0.000000,False,True,False
149,60750936,3.72,5821.82,1565.005376,61,0.010478,False,True,False
152,71353154,0.81,2117.84,2614.617284,10,0.004722,False,True,False
158,71419213,0.60,1078.60,1797.666667,6,0.005563,False,True,False
163,71606225,2.13,4218.76,1980.638498,8,0.001896,False,True,False

In [29]:

# 1. Check dataset dimensions
print("Dataset shape:", df.shape)

# 2. Check every column currently present
print("\nCurrent columns:")
for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

# 3. Check which prerequisite columns already exist
prerequisite_columns = [
    "char_count",
    "char_count_excluding_blank_marker",
    "analysis_char_count",
    "user_task_cps",
    "duration_clean",
    "task_time_clean",
    "edit_status_clean",
    "ter",
    "is_empty_submission",
    "is_blank_only_submission",
    "is_whisper_available",
    "is_duration_above_1s",
    "is_duration_above_5s",
    "is_ter_below_1",
    "is_ter_below_p1",
    "is_cps_above_p99",
    "is_transcript_unchanged",
    "is_edit_status_no",
]

print("\nPrerequisite column status:")
for col in prerequisite_columns:
    status = "EXISTS" if col in df.columns else "MISSING"
    print(f"{col}: {status}")

# 4. Confirm that no final warning flags have been created prematurely
final_flags = [
    "flag_poor_quality",
    "flag_not_listening_ter",
    "flag_cps_p99",
    "flag_rushing",
    "flag_fast_unchanged_transcript",
]

print("\nFinal warning flag status:")
for col in final_flags:
    status = "EXISTS" if col in df.columns else "NOT CREATED"
    print(f"{col}: {status}")

Dataset shape: (51783, 26)

Current columns:
1. user_id
2. recording_url
3. whisper_text
4. user_text
5. is_edited
6. duration
7. time_taken_by_user
8. segment_character_per_second
9. char_count
10. char_count_excluding_blank_marker
11. user_task_cps
12. analysis_char_count
13. duration_clean
14. task_time_clean
15. edit_status_clean
16. ter
17. flag_ter_below_1
18. flag_ter_above_50
19. flag_task_time_above_1h
20. warning_timing
21. warning_cps_support
22. warning_count_primary
23. final_flag_shorter_than_audio
24. final_flag_extreme_ter
25. final_flag_extreme_cps
26. final_flag_for_review

Prerequisite column status:
char_count: EXISTS
char_count_excluding_blank_marker: EXISTS
analysis_char_count: EXISTS
user_task_cps: EXISTS
duration_clean: EXISTS
task_time_clean: EXISTS
edit_status_clean: EXISTS
ter: EXISTS
is_empty_submission: MISSING
is_blank_only_submission: MISSING
is_whisper_available: MISSING
is_duration_above_1s: MISSING
is_duration_above_5s: MISSING
is_ter_below_1: MISSING
is_ter_below_p1: MISSING
is_cps_above_p99: MISSING
is_transcript_unchanged: MISSING
is_edit_status_no: MISSING

Final warning flag status:
flag_poor_quality: NOT CREATED
flag_not_listening_ter: NOT CREATED
flag_cps_p99: NOT CREATED
flag_rushing: NOT CREATED
flag_fast_unchanged_transcript: NOT CREATED

In [30]:

print("is_edited values:")
print(df["is_edited"].value_counts(dropna=False))

print("\nUser text examples:")
print(df["user_text"].head(10).to_list())

print("\nWhisper text examples:")
print(df["whisper_text"].head(10).to_list())

print("\nExact [blank] count:")
print(df["user_text"].astype("string").str.strip().eq("[blank]").sum())

print("\nEmpty or whitespace-only user text:")
print(
    df["user_text"].isna().sum()
    + df["user_text"].fillna("").astype(str).str.strip().eq("").sum()
)

is_edited values:
is_edited
Yes    43192
No      8591
Name: count, dtype: int64

User text examples:
[' इन जॉब में तो बहुत पैसे कमा है आपने', 'हूं ', ' तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया रुपए', 'हूं ', 'हूं ', ' पर विगराम कोई ने कोई मिल जाता है दिरीदर दोस्ती में हो जाती है एक्सीज तो फिर दिरीदर इसे जानकारी बढ़ती है मारी तो सबसे पहले', 'हां बिल्कुल क्योंकि रिश्तेदार तो हो सकते हैं दूर हो पड़ोसी तो नजदीक किया पहले भी आएंगे', 'हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही रहा था तो मुझे लगा कि अब हमें उम थोड़ा बीच में विश्राम कर लेना चाहिए तो हमने विश्राम भी किया सभी ने आराम किया वहाँ पे कुछ देर के सो गए हमने इतना कुछ खा लिया तू नींद आना शुरू हो जाती है', ' आपकी आवाज क्लियर नहीं आ रही है। हाँ, अभी आईए। हाँ, अब आ रही है।', ' हेलो आ रही है आ रही है कम कम आ रही है थोड़ी कट रही है बीच-बीच में आ रही है आप सस्ते में रुकने की बात जैसे घूमने जाते हैं उस पर जो फिर होते हैं आपने कभी नाम सुना हो तो']

Whisper text examples:
[' इन जॉब में तो बहुत पैसे कमा है आपने', nan, ' तो उसमें एक मन एक मंत की सैल्वी उसमें आठ लिया रुपए', nan, nan, ' पर विगराम कोई ने कोई मिल जाता है दिरीदर दोस्ती में हो जाती है एक्सीज तो फिर दिरीदर इसे जानकारी बढ़ती है मारी तो सबसे पहले', ' आप बिल्कुल क्योंकि वरिषिदार तो हो सकते हैं दूर हो पड़ोसी तो जजदी किया पहले भी आएंगे', 'हमने सोचा कि अब जैसे जैसे सफर आगे बढ़ता जा ही रहा था तो मुझे लगा कि अब हमें उम थोड़ा बीच में विश्राम कर लेना चाहिए तो हमने विश्राम भी किया सभी ने आराम किया वहाँ पे कुछ देर के', ' आपकी आवाज क्लियर नहीं आ रही है। हाँ, अभी आईए। हाँ, अब आ रही है।', ' हेलो आ रही है आ रही है कम कम आ रही है थोड़ी कट रही है बीच-बीच में आ रही है आप सस्ते में रुकने की बात जैसे घूमने जाते हैं उस पर जो फिर होते हैं आपने कभी नाम सुना हो तो']

Exact [blank] count:
9748

Empty or whitespace-only user text:
26

In [31]:

import numpy as np

# 1. Submission indicators
user_text_clean = df["user_text"].fillna("").astype(str).str.strip()

df["is_empty_submission"] = user_text_clean.eq("")
df["is_blank_only_submission"] = user_text_clean.eq("[blank]")

# 2. Whisper transcript availability
whisper_text_clean = df["whisper_text"].fillna("").astype(str).str.strip()
df["is_whisper_available"] = whisper_text_clean.ne("")

# 3. Audio-duration indicators
df["is_duration_above_1s"] = df["duration_clean"].gt(1)
df["is_duration_above_5s"] = df["duration_clean"].gt(5)

# 4. TER threshold
ter_valid = df["ter"].replace([np.inf, -np.inf], np.nan).dropna()

ter_p1 = ter_valid.quantile(0.01)

df["is_ter_below_1"] = df["ter"].lt(1) & df["ter"].notna()
df["is_ter_below_p1"] = df["ter"].lt(ter_p1) & df["ter"].notna()

# 5. CPS P99 threshold, calculated only for audio longer than 5 seconds
cps_valid = df.loc[
    df["is_duration_above_5s"], "user_task_cps"
].replace([np.inf, -np.inf], np.nan).dropna()

cps_p99 = cps_valid.quantile(0.99)

df["is_cps_above_p99"] = (
    df["is_duration_above_5s"]
    & df["user_task_cps"].gt(cps_p99)
    & df["user_task_cps"].notna()
)

# 6. Edit-status indicator
df["is_edit_status_no"] = (
    df["edit_status_clean"].astype("string").str.strip().str.casefold().eq("no")
)

print(f"TER P1 threshold: {ter_p1:.4f}")
print(f"CPS P99 threshold (audio > 5s): {cps_p99:.4f}")
print(f"\nDataset shape after adding prerequisites: {df.shape}")

TER P1 threshold: 0.1788
CPS P99 threshold (audio > 5s): 71.8440

Dataset shape after adding prerequisites: (51783, 35)

In [32]:

new_columns = [
    "is_empty_submission",
    "is_blank_only_submission",
    "is_whisper_available",
    "is_duration_above_1s",
    "is_duration_above_5s",
    "is_ter_below_1",
    "is_ter_below_p1",
    "is_cps_above_p99",
    "is_edit_status_no",
]

print("Prerequisite column counts:")
print(df[new_columns].sum().astype(int))

print("\nEmpty vs blank-only overlap:")
print(
    "Both true:",
    (df["is_empty_submission"] & df["is_blank_only_submission"]).sum()
)

print("\nThreshold checks:")
print("TER P1:", ter_p1)
print("TER below P1:", df["is_ter_below_p1"].sum())
print("CPS P99:", cps_p99)
print("CPS above P99:", df["is_cps_above_p99"].sum())

print("\nOriginal columns preserved:")
print(all(col in df.columns for col in df_raw.columns))

Prerequisite column counts:
is_empty_submission            26
is_blank_only_submission     9748
is_whisper_available        28681
is_duration_above_1s        37780
is_duration_above_5s        22988
is_ter_below_1               5944
is_ter_below_p1               517
is_cps_above_p99              229
is_edit_status_no               0
dtype: int64

Empty vs blank-only overlap:
Both true: 0

Threshold checks:
TER P1: 0.17875710472601664
TER below P1: 517
CPS P99: 71.84399465782435
CPS above P99: 229

Original columns preserved:
True

In [33]:

print("Original is_edited values:")
print(df["is_edited"].value_counts(dropna=False))

print("\nCleaned edit_status_clean values:")
print(df["edit_status_clean"].value_counts(dropna=False).head(20))

print("\nUnique cleaned values and representations:")
for value in df["edit_status_clean"].drop_duplicates().head(20):
    print(repr(value))

print("\nComparison checks:")
print(
    "Original equals 'No':",
    df["is_edited"].astype("string").str.strip().str.casefold().eq("no").sum()
)
print(
    "Cleaned equals 'no':",
    df["edit_status_clean"].astype("string").str.strip().str.casefold().eq("no").sum()
)

Original is_edited values:
is_edited
Yes    43192
No      8591
Name: count, dtype: int64

Cleaned edit_status_clean values:
edit_status_clean
True     43192
False     8591
Name: count, dtype: int64

Unique cleaned values and representations:
False
True

Comparison checks:
Original equals 'No': 8591
Cleaned equals 'no': 0

In [34]:

# Correctly map the Boolean cleaned column
df["is_edit_status_no"] = df["edit_status_clean"].eq(False)

print("Edit status = No:", df["is_edit_status_no"].sum())
print("Edit status = Yes:", df["edit_status_clean"].eq(True).sum())

# Verify consistency with the original column
expected_no = (
    df["is_edited"].astype("string").str.strip().str.casefold().eq("no")
)

print(
    "Mismatch with original:",
    (df["is_edit_status_no"] != expected_no).sum()
)

Edit status = No: 8591
Edit status = Yes: 43192
Mismatch with original: 0

In [35]:

import pandas as pd

# Normalize transcripts for comparison without modifying original text
user_norm = (
    df["user_text"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.split()
    .str.join(" ")
)

whisper_norm = (
    df["whisper_text"]
    .fillna("")
    .astype(str)
    .str.lower()
    .str.split()
    .str.join(" ")
)

# Require both transcripts to be available and non-empty
both_transcripts_available = user_norm.ne("") & whisper_norm.ne("")

df["is_transcript_unchanged"] = (
    both_transcripts_available
    & user_norm.eq(whisper_norm)
)

# Validation
print("Unchanged transcript count:", df["is_transcript_unchanged"].sum())
print(
    "Unchanged AND edit status No:",
    (df["is_transcript_unchanged"] & df["is_edit_status_no"]).sum()
)
print(
    "Unchanged but either transcript missing/empty:",
    (
        df["is_transcript_unchanged"]
        & ~both_transcripts_available
    ).sum()
)
print(
    "Edit status No:",
    df["is_edit_status_no"].sum()
)

Unchanged transcript count: 9139
Unchanged AND edit status No: 8591
Unchanged but either transcript missing/empty: 0
Edit status No: 8591

In [36]:

print("Edit status vs transcript comparison:")
print(
    pd.crosstab(
        df["edit_status_clean"],
        df["is_transcript_unchanged"],
        margins=True
    )
)

print("\nEdit status No, but transcript changed:")
print(
    (
        df["is_edit_status_no"]
        & ~df["is_transcript_unchanged"]
    ).sum()
)

print("\nEdit status Yes, but transcript unchanged:")
print(
    (
        df["edit_status_clean"].eq(True)
        & df["is_transcript_unchanged"]
    ).sum()
)

Edit status vs transcript comparison:
is_transcript_unchanged  False  True    All
edit_status_clean
False                        0  8591   8591
True                     42644   548  43192
All                      42644  9139  51783

Edit status No, but transcript changed:
0

Edit status Yes, but transcript unchanged:
548

In [37]:

# Compare the candidate rushing signals
ter_p1_signal = df["is_ter_below_p1"]
cps_p99_signal = df["is_cps_above_p99"]

print("TER < P1:", int(ter_p1_signal.sum()))
print("CPS > P99:", int(cps_p99_signal.sum()))

print("\nOverlap:")
print("Both signals:", int((ter_p1_signal & cps_p99_signal).sum()))
print("TER P1 only:", int((ter_p1_signal & ~cps_p99_signal).sum()))
print("CPS P99 only:", int((cps_p99_signal & ~ter_p1_signal).sum()))
print("Either signal:", int((ter_p1_signal | cps_p99_signal).sum()))

print("\nTER < 1 with audio > 1 second:")
print(
    int(
        (
            df["is_ter_below_1"]
            & df["is_duration_above_1s"]
        ).sum()
    )
)

print("\nEmpty or blank-only submission with Whisper available:")
print(
    int(
        (
            (df["is_empty_submission"] | df["is_blank_only_submission"])
            & df["is_whisper_available"]
            & df["is_duration_above_1s"]
        ).sum()
    )
)

TER < P1: 517
CPS > P99: 229

Overlap:
Both signals: 212
TER P1 only: 305
CPS P99 only: 17
Either signal: 534

TER < 1 with audio > 1 second:
5939

Empty or blank-only submission with Whisper available:
1019

In [38]:

# Inspect the composition of the 1,019 candidate records
candidate_mask = (
    (df["is_empty_submission"] | df["is_blank_only_submission"])
    & df["is_whisper_available"]
    & df["is_duration_above_1s"]
)

candidates = df.loc[candidate_mask]

print("Total candidates:", len(candidates))

print("\nSubmission type:")
print(
    candidates.assign(
        submission_type=np.where(
            candidates["is_blank_only_submission"],
            "[blank] only",
            "Empty/whitespace"
        )
    )["submission_type"].value_counts()
)

print("\nEdit status:")
print(candidates["edit_status_clean"].value_counts(dropna=False))

print("\nAudio duration summary:")
print(candidates["duration_clean"].describe())

print("\nSample records:")
display(
    candidates[
        [
            "user_id",
            "duration_clean",
            "whisper_text",
            "user_text",
            "edit_status_clean",
            "ter"
        ]
    ].head(10)
)

Total candidates: 1019

Submission type:
submission_type
[blank] only        1010
Empty/whitespace       9
Name: count, dtype: int64

Edit status:
edit_status_clean
True    1019
Name: count, dtype: int64

Audio duration summary:
count    1019.000000
mean        1.678332
std         0.777987
min         1.020000
25%         1.200000
50%         1.500000
75%         1.980000
max        13.170000
Name: duration_clean, dtype: float64

Sample records:

,user_id,duration_clean,whisper_text,user_text,edit_status_clean,ter
142,73636811,1.23,प्रस्तुति प्रस्तुति,[blank],True,9.471545
434,71420491,2.13,पूर्ट पर दिया वाला से जिन्ने पर यह नहीं रखेगा,[blank],True,4.197183
532,71716111,1.65,अच्छा अच्छा,[blank],True,2.842424
591,72370108,1.26,सुभाग,[blank],True,7.261905
616,72464859,1.08,प्रस्तुति प्रस्तुति,[blank],True,5.231481
630,74986272,2.00,लेकिन चोटी बच्चो को,[blank],True,5.110000
741,71126366,1.02,प्रस्तुति प्रस्तुति,[blank],True,10.950980
924,71356775,1.53,प्रस्तुति प्रस्तुति,[blank],True,7.143791
1134,71958800,1.14,झाल,[blank],True,3.736842
1146,72179550,1.11,झाल,[blank],True,232.864865

In [39]:

display(
    candidates[
        [
            "duration_clean",
            "whisper_text",
            "user_text",
            "edit_status_clean",
            "ter"
        ]
    ].sample(min(15, len(candidates)), random_state=42)
)

,duration_clean,whisper_text,user_text,edit_status_clean,ter
30957,1.71,प्रस्तुति प्रस्तुति,[blank],True,0.807018
26796,1.29,अजय को,[blank],True,10.232558
26236,1.47,अजय को,[blank],True,4.013605
2063,2.01,प्रस्तुति प्रस्तुति,[blank],True,0.940299
34928,1.17,"जी, जी, जी.",[blank],True,0.931624
32363,1.80,पाग,[blank],True,20.183333
26278,1.35,प्रस्तुति प्रस्तुति,[blank],True,2.577778
38663,1.08,प्रस्तुति प्रस्तुति,[blank],True,1.777778
5092,1.77,आज,[blank],True,2.514124
29994,2.76,प्रस्तुति प्रस्तुति,[blank],True,1.789855
37665,1.17,प्रस्तुति प्रस्तुति,[blank],True,4.162393
4587,1.65,"आहां, तो चलिए ना",[blank],True,3.666667
45133,1.44,प्रस्तुति प्रस्तुति,[blank],True,1.708333
6684,1.53,झाल,[blank],True,4.607843
34980,1.65,बाहर,[blank],True,0.951515

In [40]:

# Show current table structure without modifying df

original_columns = [
    "user_id",
    "recording_url",
    "whisper_text",
    "user_text",
    "is_edited",
    "duration",
    "time_taken_by_user",
    "segment_character_per_second",
]

analysis_columns = [
    "char_count",
    "char_count_excluding_blank_marker",
    "user_task_cps",
    "analysis_char_count",
    "duration_clean",
    "task_time_clean",
    "edit_status_clean",
    "ter",
]

existing_warning_columns = [
    "flag_ter_below_1",
    "flag_ter_above_50",
    "flag_task_time_above_1h",
    "warning_timing",
    "warning_cps_support",
    "warning_count_primary",
    "final_flag_shorter_than_audio",
    "final_flag_extreme_ter",
    "final_flag_extreme_cps",
    "final_flag_for_review",
]

prerequisite_columns = [
    "is_empty_submission",
    "is_blank_only_submission",
    "is_whisper_available",
    "is_duration_above_1s",
    "is_duration_above_5s",
    "is_ter_below_1",
    "is_ter_below_p1",
    "is_cps_above_p99",
    "is_edit_status_no",
    "is_transcript_unchanged",
]

groups = {
    "Original columns": original_columns,
    "Analysis columns": analysis_columns,
    "Existing warning columns": existing_warning_columns,
    "Prerequisite columns": prerequisite_columns,
}

print(f"Dataset shape: {df.shape}")

for group_name, columns in groups.items():
    print(f"\n{group_name} ({len(columns)} columns):")
    for col in columns:
        status = "EXISTS" if col in df.columns else "MISSING"
        print(f"  {col}: {status}")

print("\nAll columns currently in df:")
print(df.columns.tolist())

print("\nFirst 5 rows of the full table:")
display(df.head())

Dataset shape: (51783, 36)

Original columns (8 columns):
  user_id: EXISTS
  recording_url: EXISTS
  whisper_text: EXISTS
  user_text: EXISTS
  is_edited: EXISTS
  duration: EXISTS
  time_taken_by_user: EXISTS
  segment_character_per_second: EXISTS

Analysis columns (8 columns):
  char_count: EXISTS
  char_count_excluding_blank_marker: EXISTS
  user_task_cps: EXISTS
  analysis_char_count: EXISTS
  duration_clean: EXISTS
  task_time_clean: EXISTS
  edit_status_clean: EXISTS
  ter: EXISTS

Existing warning columns (10 columns):
  flag_ter_below_1: EXISTS
  flag_ter_above_50: EXISTS
  flag_task_time_above_1h: EXISTS
  warning_timing: EXISTS
  warning_cps_support: EXISTS
  warning_count_primary: EXISTS
  final_flag_shorter_than_audio: EXISTS
  final_flag_extreme_ter: EXISTS
  final_flag_extreme_cps: EXISTS
  final_flag_for_review: EXISTS

Prerequisite columns (10 columns):
  is_empty_submission: EXISTS
  is_blank_only_submission: EXISTS
  is_whisper_available: EXISTS
  is_duration_above_1s: EXISTS
  is_duration_above_5s: EXISTS
  is_ter_below_1: EXISTS
  is_ter_below_p1: EXISTS
  is_cps_above_p99: EXISTS
  is_edit_status_no: EXISTS
  is_transcript_unchanged: EXISTS

All columns currently in df:
['user_id', 'recording_url', 'whisper_text', 'user_text', 'is_edited', 'duration', 'time_taken_by_user', 'segment_character_per_second', 'char_count', 'char_count_excluding_blank_marker', 'user_task_cps', 'analysis_char_count', 'duration_clean', 'task_time_clean', 'edit_status_clean', 'ter', 'flag_ter_below_1', 'flag_ter_above_50', 'flag_task_time_above_1h', 'warning_timing', 'warning_cps_support', 'warning_count_primary', 'final_flag_shorter_than_audio', 'final_flag_extreme_ter', 'final_flag_extreme_cps', 'final_flag_for_review', 'is_empty_submission', 'is_blank_only_submission', 'is_whisper_available', 'is_duration_above_1s', 'is_duration_above_5s', 'is_ter_below_1', 'is_ter_below_p1', 'is_cps_above_p99', 'is_edit_status_no', 'is_transcript_unchanged']

First 5 rows of the full table:

,user_id,recording_url,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second,char_count,char_count_excluding_blank_marker,...,is_empty_submission,is_blank_only_submission,is_whisper_available,is_duration_above_1s,is_duration_above_5s,is_ter_below_1,is_ter_below_p1,is_cps_above_p99,is_edit_status_no,is_transcript_unchanged
0,71275781,https://storage.googleapis.com/joshtalks-data-...,इन जॉब में तो बहुत पैसे कमा है आपने,इन जॉब में तो बहुत पैसे कमा है आपने,No,2.94,15.00,9.18,27,27,...,False,False,True,True,False,False,False,False,True,True
1,71275800,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.96,14.26,3.13,3,3,...,False,False,False,False,False,False,False,False,False,False
2,71275813,https://storage.googleapis.com/joshtalks-data-...,तो उसमें एक मन एक मंत की सैल्वी उसमें आठ लिया...,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,Yes,4.83,20.85,7.87,38,38,...,False,False,True,True,False,False,False,False,False,False
3,71275842,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.45,8.46,6.67,3,3,...,False,False,False,False,False,False,False,False,False,False
4,71275856,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.27,11.65,11.11,3,3,...,False,False,False,False,False,False,False,False,False,False

In [41]:

# Keep original data and only the useful analysis/prerequisite columns

keep_columns = [
    # Original columns
    "user_id",
    "recording_url",
    "whisper_text",
    "user_text",
    "is_edited",
    "duration",
    "time_taken_by_user",
    "segment_character_per_second",

    # Core metrics
    "analysis_char_count",
    "duration_clean",
    "task_time_clean",
    "user_task_cps",
    "ter",
    "edit_status_clean",

    # Submission checks
    "is_empty_submission",
    "is_blank_only_submission",
    "is_whisper_available",

    # Threshold checks
    "is_duration_above_1s",
    "is_duration_above_5s",
    "is_ter_below_1",
    "is_ter_below_p1",
    "is_cps_above_p99",

    # Transcript checks
    "is_transcript_unchanged",
    "is_edit_status_no",
]

# Verify all requested columns exist before selecting
missing_columns = [col for col in keep_columns if col not in df.columns]

if missing_columns:
    raise ValueError(f"Missing required columns: {missing_columns}")

df_clean = df[keep_columns].copy()

print("Cleaned dataset shape:", df_clean.shape)
print("\nRemaining columns:")
print(df_clean.columns.tolist())

display(df_clean.head())

Cleaned dataset shape: (51783, 24)

Remaining columns:
['user_id', 'recording_url', 'whisper_text', 'user_text', 'is_edited', 'duration', 'time_taken_by_user', 'segment_character_per_second', 'analysis_char_count', 'duration_clean', 'task_time_clean', 'user_task_cps', 'ter', 'edit_status_clean', 'is_empty_submission', 'is_blank_only_submission', 'is_whisper_available', 'is_duration_above_1s', 'is_duration_above_5s', 'is_ter_below_1', 'is_ter_below_p1', 'is_cps_above_p99', 'is_transcript_unchanged', 'is_edit_status_no']

,user_id,recording_url,whisper_text,user_text,is_edited,duration,time_taken_by_user,segment_character_per_second,analysis_char_count,duration_clean,...,is_empty_submission,is_blank_only_submission,is_whisper_available,is_duration_above_1s,is_duration_above_5s,is_ter_below_1,is_ter_below_p1,is_cps_above_p99,is_transcript_unchanged,is_edit_status_no
0,71275781,https://storage.googleapis.com/joshtalks-data-...,इन जॉब में तो बहुत पैसे कमा है आपने,इन जॉब में तो बहुत पैसे कमा है आपने,No,2.94,15.00,9.18,27,2.94,...,False,False,True,True,False,False,False,False,True,True
1,71275800,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.96,14.26,3.13,3,0.96,...,False,False,False,False,False,False,False,False,False,False
2,71275813,https://storage.googleapis.com/joshtalks-data-...,तो उसमें एक मन एक मंत की सैल्वी उसमें आठ लिया...,तो उसमें एक मन एक मंत की सैलरी उसमें आठ लिया ...,Yes,4.83,20.85,7.87,38,4.83,...,False,False,True,True,False,False,False,False,False,False
3,71275842,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.45,8.46,6.67,3,0.45,...,False,False,False,False,False,False,False,False,False,False
4,71275856,https://storage.googleapis.com/joshtalks-data-...,NaN,हूं,Yes,0.27,11.65,11.11,3,0.27,...,False,False,False,False,False,False,False,False,False,False

In [42]:

# Warning sign 1: Blank/incomplete submission despite available Whisper text
df_clean["flag_blank_submission"] = (
    (df_clean["is_empty_submission"] | df_clean["is_blank_only_submission"])
    & df_clean["is_whisper_available"]
    & df_clean["is_duration_above_1s"]
)

# Warning sign 2: Extremely low time-to-audio ratio (bottom 1%)
df_clean["flag_extreme_low_ter"] = (
    df_clean["is_ter_below_p1"]
    & df_clean["is_duration_above_1s"]
)

# Warning sign 3: Task completed faster than the audio duration
df_clean["flag_ter_below_1"] = (
    df_clean["is_ter_below_1"]
    & df_clean["is_duration_above_1s"]
)

# Warning sign 4: Extremely high character production rate (top 1%)
df_clean["flag_extreme_cps"] = (
    df_clean["is_cps_above_p99"]
    & df_clean["is_duration_above_1s"]
)

# Validate counts
warning_cols = [
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps"
]

print("Warning sign counts:")
print(df_clean[warning_cols].sum().sort_values(ascending=False))

print("\nNumber of tasks with at least one warning:")
print(df_clean[warning_cols].any(axis=1).sum())

Warning sign counts:
flag_ter_below_1         5939
flag_blank_submission    1019
flag_extreme_low_ter      517
flag_extreme_cps          229
dtype: int64

Number of tasks with at least one warning:
6832

In [43]:


print("Warning sign overlap matrix:")
print(df_clean[warning_cols].astype(int).T.dot(
    df_clean[warning_cols].astype(int)
))

Warning sign overlap matrix:
                       flag_blank_submission  flag_extreme_low_ter  \
flag_blank_submission                   1019                     0
flag_extreme_low_ter                       0                   517
flag_ter_below_1                         126                   517
flag_extreme_cps                           0                   212

                       flag_ter_below_1  flag_extreme_cps
flag_blank_submission               126                 0
flag_extreme_low_ter                517               212
flag_ter_below_1                   5939               229
flag_extreme_cps                    229               229

In [44]:

user_summary = (
    df_clean.groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        blank_submission_tasks=("flag_blank_submission", "sum"),
        extreme_low_ter_tasks=("flag_extreme_low_ter", "sum"),
        ter_below_1_tasks=("flag_ter_below_1", "sum"),
        extreme_cps_tasks=("flag_extreme_cps", "sum")
    )
    .reset_index()
)

user_summary["tasks_with_any_warning"] = (
    df_clean.assign(
        any_warning=df_clean[warning_cols].any(axis=1)
    )
    .groupby("user_id")["any_warning"]
    .sum()
    .to_numpy()
)

user_summary["warning_rate"] = (
    user_summary["tasks_with_any_warning"] / user_summary["total_tasks"]
)

user_summary = user_summary.sort_values(
    ["tasks_with_any_warning", "total_tasks"],
    ascending=False
)

display(user_summary.head(20))

,user_id,total_tasks,blank_submission_tasks,extreme_low_ter_tasks,ter_below_1_tasks,extreme_cps_tasks,tasks_with_any_warning,warning_rate
6,580062,609,7,0,164,0,171,0.280788
3,393886,509,4,0,123,0,127,0.249509
4,410566,349,0,0,105,0,105,0.300860
8,681509,358,1,0,99,0,100,0.279330
0,222099,333,0,0,89,0,89,0.267267
1,311760,184,0,0,57,0,57,0.309783
7,632098,165,2,0,54,0,56,0.339394
5,467270,176,0,0,50,0,50,0.284091
2,326611,149,2,0,35,0,37,0.248322
9,688393,86,0,0,27,0,27,0.313953
15,56567741,1,0,0,1,0,1,1.000000
19,56568526,1,0,0,1,0,1,1.000000
72,56599460,1,0,0,1,0,1,1.000000
79,56599941,1,0,0,1,0,1,1.000000
142,56604793,1,0,0,1,0,1,1.000000
159,56606274,1,0,0,1,0,1,1.000000
192,56630280,1,0,0,1,0,1,1.000000
205,56632603,1,0,0,1,0,1,1.000000
208,56632996,1,0,0,1,0,1,1.000000
218,56633553,1,0,0,1,0,1,1.000000

In [45]:

# 1. Validate the warning flags
warning_cols = [
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps"
]

print("Flag counts:")
print(df_clean[warning_cols].sum())

print("\nTasks with at least one warning:")
print(df_clean[warning_cols].any(axis=1).sum())

print("\nOverlap matrix:")
print(df_clean[warning_cols].astype(int).T.dot(
    df_clean[warning_cols].astype(int)
))

# 2. Rebuild user-level summary safely
df_clean["any_warning"] = df_clean[warning_cols].any(axis=1)

user_summary = (
    df_clean.groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        blank_submission_tasks=("flag_blank_submission", "sum"),
        extreme_low_ter_tasks=("flag_extreme_low_ter", "sum"),
        ter_below_1_tasks=("flag_ter_below_1", "sum"),
        extreme_cps_tasks=("flag_extreme_cps", "sum"),
        tasks_with_any_warning=("any_warning", "sum")
    )
    .reset_index()
)

user_summary["warning_rate"] = (
    user_summary["tasks_with_any_warning"] / user_summary["total_tasks"]
)

user_summary = user_summary.sort_values(
    ["tasks_with_any_warning", "total_tasks"],
    ascending=False
)

# 3. Sanity checks: user totals must reconcile with task-level totals
print("\nValidation checks:")
print("Users in summary:", user_summary["user_id"].nunique())
print("Tasks accounted for:", user_summary["total_tasks"].sum())
print("Dataset rows:", len(df_clean))
print(
    "User-level warning tasks:",
    user_summary["tasks_with_any_warning"].sum()
)
print(
    "Task-level warning union:",
    df_clean["any_warning"].sum()
)

# Show users with at least 20 tasks first
display(
    user_summary[user_summary["total_tasks"] >= 20].head(20)
)

Flag counts:
flag_blank_submission    1019
flag_extreme_low_ter      517
flag_ter_below_1         5939
flag_extreme_cps          229
dtype: int64

Tasks with at least one warning:
6832

Overlap matrix:
                       flag_blank_submission  flag_extreme_low_ter  \
flag_blank_submission                   1019                     0
flag_extreme_low_ter                       0                   517
flag_ter_below_1                         126                   517
flag_extreme_cps                           0                   212

                       flag_ter_below_1  flag_extreme_cps
flag_blank_submission               126                 0
flag_extreme_low_ter                517               212
flag_ter_below_1                   5939               229
flag_extreme_cps                    229               229

Validation checks:
Users in summary: 48875
Tasks accounted for: 51783
Dataset rows: 51783
User-level warning tasks: 6832
Task-level warning union: 6832

,user_id,total_tasks,blank_submission_tasks,extreme_low_ter_tasks,ter_below_1_tasks,extreme_cps_tasks,tasks_with_any_warning,warning_rate
6,580062,609,7,0,164,0,171,0.280788
3,393886,509,4,0,123,0,127,0.249509
4,410566,349,0,0,105,0,105,0.300860
8,681509,358,1,0,99,0,100,0.279330
0,222099,333,0,0,89,0,89,0.267267
1,311760,184,0,0,57,0,57,0.309783
7,632098,165,2,0,54,0,56,0.339394
5,467270,176,0,0,50,0,50,0.284091
2,326611,149,2,0,35,0,37,0.248322
9,688393,86,0,0,27,0,27,0.313953

In [46]:

# Calculate CPS thresholds using the same population as before:
# tasks with audio duration > 5 seconds
cps_population = df_clean.loc[
    df_clean["is_duration_above_5s"]
    & df_clean["user_task_cps"].notna(),
    "user_task_cps"
]

cps_p98 = cps_population.quantile(0.98)
cps_p99 = cps_population.quantile(0.99)

print(f"CPS P98 threshold: {cps_p98:.3f} characters/second")
print(f"CPS P99 threshold: {cps_p99:.3f} characters/second")

# Compare the number of flagged tasks
print("\nTasks flagged:")
print("Top 2%:", (cps_population > cps_p98).sum())
print("Top 1%:", (cps_population > cps_p99).sum())

# Update the CPS warning flag to use P98
df_clean["is_cps_above_p98"] = (
    df_clean["is_duration_above_5s"]
    & df_clean["user_task_cps"].gt(cps_p98)
)

df_clean["flag_extreme_cps"] = (
    df_clean["is_cps_above_p98"]
    & df_clean["is_duration_above_1s"]
)

print("\nUpdated CPS warning count:",
      df_clean["flag_extreme_cps"].sum())

CPS P98 threshold: 59.858 characters/second
CPS P99 threshold: 71.844 characters/second

Tasks flagged:
Top 2%: 457
Top 1%: 229

Updated CPS warning count: 457

In [47]:

warning_cols = [
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps"
]

print("Updated warning counts:")
print(df_clean[warning_cols].sum().sort_values(ascending=False))

print("\nUpdated overlap matrix:")
print(df_clean[warning_cols].astype(int).T.dot(
    df_clean[warning_cols].astype(int)
))

df_clean["any_warning"] = df_clean[warning_cols].any(axis=1)

print("\nTasks with at least one warning:",
      df_clean["any_warning"].sum())

print("Tasks with no warnings:",
      (~df_clean["any_warning"]).sum())

Updated warning counts:
flag_ter_below_1         5939
flag_blank_submission    1019
flag_extreme_low_ter      517
flag_extreme_cps          457
dtype: int64

Updated overlap matrix:
                       flag_blank_submission  flag_extreme_low_ter  \
flag_blank_submission                   1019                     0
flag_extreme_low_ter                       0                   517
flag_ter_below_1                         126                   517
flag_extreme_cps                           0                   346

                       flag_ter_below_1  flag_extreme_cps
flag_blank_submission               126                 0
flag_extreme_low_ter                517               346
flag_ter_below_1                   5939               457
flag_extreme_cps                    457               457

Tasks with at least one warning: 6832
Tasks with no warnings: 44951

In [48]:

warning_cols = [
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps"
]

print("Updated warning counts:")
print(df_clean[warning_cols].sum().sort_values(ascending=False))

print("\nUpdated overlap matrix:")
print(df_clean[warning_cols].astype(int).T.dot(
    df_clean[warning_cols].astype(int)
))

df_clean["any_warning"] = df_clean[warning_cols].any(axis=1)

print("\nTasks with at least one warning:",
      df_clean["any_warning"].sum())

print("Tasks with no warnings:",
      (~df_clean["any_warning"]).sum())

Updated warning counts:
flag_ter_below_1         5939
flag_blank_submission    1019
flag_extreme_low_ter      517
flag_extreme_cps          457
dtype: int64

Updated overlap matrix:
                       flag_blank_submission  flag_extreme_low_ter  \
flag_blank_submission                   1019                     0
flag_extreme_low_ter                       0                   517
flag_ter_below_1                         126                   517
flag_extreme_cps                           0                   346

                       flag_ter_below_1  flag_extreme_cps
flag_blank_submission               126                 0
flag_extreme_low_ter                517               346
flag_ter_below_1                   5939               457
flag_extreme_cps                    457               457

Tasks with at least one warning: 6832
Tasks with no warnings: 44951

In [49]:

# Rebuild user-level summary using the current four warning flags
warning_cols = [
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps"
]

df_clean["any_warning"] = df_clean[warning_cols].any(axis=1)

user_summary = (
    df_clean.groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        blank_submission_tasks=("flag_blank_submission", "sum"),
        extreme_low_ter_tasks=("flag_extreme_low_ter", "sum"),
        ter_below_1_tasks=("flag_ter_below_1", "sum"),
        extreme_cps_tasks=("flag_extreme_cps", "sum"),
        tasks_with_any_warning=("any_warning", "sum")
    )
    .reset_index()
)

user_summary["warning_rate"] = (
    user_summary["tasks_with_any_warning"] / user_summary["total_tasks"]
)

print("Rows in dataset:", len(df_clean))
print("Tasks represented in user summary:", user_summary["total_tasks"].sum())
print("Unique users:", user_summary["user_id"].nunique())
print("Warning tasks, task-level:", df_clean["any_warning"].sum())
print("Warning tasks, user-level sum:",
      user_summary["tasks_with_any_warning"].sum())

# Focus on users with enough tasks for a meaningful pattern
display(
    user_summary[user_summary["total_tasks"] >= 20]
    .sort_values("warning_rate", ascending=False)
    .head(20)
)

Rows in dataset: 51783
Tasks represented in user summary: 51783
Unique users: 48875
Warning tasks, task-level: 6832
Warning tasks, user-level sum: 6832

,user_id,total_tasks,blank_submission_tasks,extreme_low_ter_tasks,ter_below_1_tasks,extreme_cps_tasks,tasks_with_any_warning,warning_rate
7,632098,165,2,0,54,0,56,0.339394
9,688393,86,0,0,27,0,27,0.313953
1,311760,184,0,0,57,0,57,0.309783
4,410566,349,0,0,105,0,105,0.300860
5,467270,176,0,0,50,0,50,0.284091
6,580062,609,7,0,164,0,171,0.280788
8,681509,358,1,0,99,0,100,0.279330
0,222099,333,0,0,89,0,89,0.267267
3,393886,509,4,0,123,0,127,0.249509
2,326611,149,2,0,35,0,37,0.248322

In [50]:

# Number of tasks completed by each user
tasks_per_user = df_clean.groupby("user_id").size()

# Summary statistics
print("Total unique users:", tasks_per_user.size)
print("\nTasks per user summary:")
display(tasks_per_user.describe().to_frame("task_count"))

# Distribution: how many users completed N tasks
task_distribution = (
    tasks_per_user.value_counts()
    .sort_index()
    .rename_axis("tasks_per_user")
    .reset_index(name="number_of_users")
)

display(task_distribution.head(30))

Total unique users: 48875

Tasks per user summary:

         task_count
count  48875.000000
mean       1.059499
std        4.758073
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max      609.000000

    tasks_per_user  number_of_users
0                1            48865
1               86                1
2              149                1
3              165                1
4              176                1
5              184                1
6              333                1
7              349                1
8              358                1
9              509                1
10             609                1

In [52]:

# Group users into task-count ranges
task_bins = [
    ("1 task", tasks_per_user.eq(1)),
    ("2–5 tasks", tasks_per_user.between(2, 5)),
    ("6–10 tasks", tasks_per_user.between(6, 10)),
    ("11–20 tasks", tasks_per_user.between(11, 20)),
    ("21–50 tasks", tasks_per_user.between(21, 50)),
    ("More than 50 tasks", tasks_per_user.gt(50)),
]

distribution_summary = pd.DataFrame([
    {
        "task_range": label,
        "number_of_users": int(mask.sum()),
        "percentage_of_users": round(mask.mean() * 100, 2)
    }
    for label, mask in task_bins
])

display(distribution_summary)

           task_range  number_of_users  percentage_of_users
0              1 task            48865                99.98
1           2–5 tasks                0                 0.00
2          6–10 tasks                0                 0.00
3         11–20 tasks                0                 0.00
4         21–50 tasks                0                 0.00
5  More than 50 tasks               10                 0.02

In [53]:

warning_cols = [
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps"
]

summary = pd.DataFrame({
    "warning_sign": warning_cols,
    "flagged_tasks": [int(df_clean[c].sum()) for c in warning_cols],
    "percentage_of_all_tasks": [
        round(df_clean[c].mean() * 100, 2) for c in warning_cols
    ]
})

summary.loc[len(summary)] = [
    "any_warning",
    int(df_clean[warning_cols].any(axis=1).sum()),
    round(df_clean[warning_cols].any(axis=1).mean() * 100, 2)
]

display(summary)

            warning_sign  flagged_tasks  percentage_of_all_tasks
0  flag_blank_submission           1019                     1.97
1   flag_extreme_low_ter            517                     1.00
2       flag_ter_below_1           5939                    11.47
3       flag_extreme_cps            457                     0.88
4            any_warning           6832                    13.19

In [54]:

# Provisional task-level warning weights
weights = {
    "flag_blank_submission": 4,
    "flag_extreme_low_ter": 3,
    "flag_ter_below_1": 1,
    "flag_extreme_cps": 2
}

# Calculate weighted score for each task
df_clean["task_risk_score"] = sum(
    df_clean[col].astype(int) * weight
    for col, weight in weights.items()
)

# Aggregate scores by user
user_risk = (
    df_clean.groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        total_risk_score=("task_risk_score", "sum"),
        flagged_tasks=("any_warning", "sum"),
        blank_tasks=("flag_blank_submission", "sum"),
        extreme_low_ter_tasks=("flag_extreme_low_ter", "sum"),
        ter_below_1_tasks=("flag_ter_below_1", "sum"),
        extreme_cps_tasks=("flag_extreme_cps", "sum")
    )
    .reset_index()
)

# Normalize to a percentage of the maximum possible score
user_risk["risk_rate_pct"] = (
    user_risk["total_risk_score"]
    / (user_risk["total_tasks"] * sum(weights.values()))
    * 100
)

user_risk["flagged_task_rate_pct"] = (
    user_risk["flagged_tasks"]
    / user_risk["total_tasks"]
    * 100
)

display(
    user_risk.sort_values(
        ["risk_rate_pct", "flagged_tasks"],
        ascending=False
    ).head(20)
)

,user_id,total_tasks,total_risk_score,flagged_tasks,blank_tasks,extreme_low_ter_tasks,ter_below_1_tasks,extreme_cps_tasks,risk_rate_pct,flagged_task_rate_pct
4467,71039477,1,6,1,0,1,1,1,60.0,100.0
4477,71039528,1,6,1,0,1,1,1,60.0,100.0
4584,71041236,1,6,1,0,1,1,1,60.0,100.0
4733,71043852,1,6,1,0,1,1,1,60.0,100.0
4753,71044053,1,6,1,0,1,1,1,60.0,100.0
4754,71044058,1,6,1,0,1,1,1,60.0,100.0
4767,71044420,1,6,1,0,1,1,1,60.0,100.0
4844,71046140,1,6,1,0,1,1,1,60.0,100.0
4920,71048171,1,6,1,0,1,1,1,60.0,100.0
4926,71048210,1,6,1,0,1,1,1,60.0,100.0
4980,71048821,1,6,1,0,1,1,1,60.0,100.0
5066,71049934,1,6,1,0,1,1,1,60.0,100.0
5323,71122999,1,6,1,0,1,1,1,60.0,100.0
5457,71124901,1,6,1,0,1,1,1,60.0,100.0
5458,71124903,1,6,1,0,1,1,1,60.0,100.0
5896,71131136,1,6,1,0,1,1,1,60.0,100.0
7228,71277583,1,6,1,0,1,1,1,60.0,100.0
7536,71281446,1,6,1,0,1,1,1,60.0,100.0
7911,71347643,1,6,1,0,1,1,1,60.0,100.0
7944,71347911,1,6,1,0,1,1,1,60.0,100.0

In [55]:

# Keep the agreed weights, but avoid double-counting TER signals
df_clean["task_risk_score_adjusted"] = (
    df_clean["flag_blank_submission"].astype(int) * 4
    + df_clean["flag_extreme_low_ter"].astype(int) * 3
    + (
        df_clean["flag_ter_below_1"]
        & ~df_clean["flag_extreme_low_ter"]
    ).astype(int) * 1
    + df_clean["flag_extreme_cps"].astype(int) * 2
)

user_risk = (
    df_clean.groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        total_risk_score=("task_risk_score_adjusted", "sum"),
        flagged_tasks=("any_warning", "sum"),
        blank_tasks=("flag_blank_submission", "sum"),
        extreme_low_ter_tasks=("flag_extreme_low_ter", "sum"),
        ter_below_1_tasks=("flag_ter_below_1", "sum"),
        extreme_cps_tasks=("flag_extreme_cps", "sum")
    )
    .reset_index()
)

user_risk["risk_rate_pct"] = (
    user_risk["total_risk_score"]
    / (user_risk["total_tasks"] * 10)
    * 100
)

user_risk["flagged_task_rate_pct"] = (
    user_risk["flagged_tasks"]
    / user_risk["total_tasks"]
    * 100
)

display(
    user_risk.sort_values(
        ["risk_rate_pct", "total_tasks"],
        ascending=False
    ).head(20)
)

,user_id,total_tasks,total_risk_score,flagged_tasks,blank_tasks,extreme_low_ter_tasks,ter_below_1_tasks,extreme_cps_tasks,risk_rate_pct,flagged_task_rate_pct
4467,71039477,1,5,1,0,1,1,1,50.0,100.0
4477,71039528,1,5,1,0,1,1,1,50.0,100.0
4533,71040194,1,5,1,1,0,1,0,50.0,100.0
4584,71041236,1,5,1,0,1,1,1,50.0,100.0
4652,71042597,1,5,1,1,0,1,0,50.0,100.0
4677,71042890,1,5,1,1,0,1,0,50.0,100.0
4733,71043852,1,5,1,0,1,1,1,50.0,100.0
4753,71044053,1,5,1,0,1,1,1,50.0,100.0
4754,71044058,1,5,1,0,1,1,1,50.0,100.0
4767,71044420,1,5,1,0,1,1,1,50.0,100.0
4844,71046140,1,5,1,0,1,1,1,50.0,100.0
4884,71047782,1,5,1,1,0,1,0,50.0,100.0
4920,71048171,1,5,1,0,1,1,1,50.0,100.0
4926,71048210,1,5,1,0,1,1,1,50.0,100.0
4980,71048821,1,5,1,0,1,1,1,50.0,100.0
5023,71049305,1,5,1,1,0,1,0,50.0,100.0
5066,71049934,1,5,1,0,1,1,1,50.0,100.0
5220,71121298,1,5,1,1,0,1,0,50.0,100.0
5323,71122999,1,5,1,0,1,1,1,50.0,100.0
5457,71124901,1,5,1,0,1,1,1,50.0,100.0

In [56]:

repeat_suspicious_users = user_risk[
    (user_risk["total_tasks"] > 1)
    & (user_risk["flagged_tasks"] > 1)
].sort_values(
    ["flagged_tasks", "risk_rate_pct"],
    ascending=False
)

print("Users with multiple tasks and multiple flagged tasks:",
      len(repeat_suspicious_users))

display(repeat_suspicious_users.head(20))

Users with multiple tasks and multiple flagged tasks: 10

,user_id,total_tasks,total_risk_score,flagged_tasks,blank_tasks,extreme_low_ter_tasks,ter_below_1_tasks,extreme_cps_tasks,risk_rate_pct,flagged_task_rate_pct
6,580062,609,192,171,7,0,164,0,3.152709,28.078818
3,393886,509,139,127,4,0,123,0,2.730845,24.950884
4,410566,349,105,105,0,0,105,0,3.008596,30.085960
8,681509,358,103,100,1,0,99,0,2.877095,27.932961
0,222099,333,89,89,0,0,89,0,2.672673,26.726727
1,311760,184,57,57,0,0,57,0,3.097826,30.978261
7,632098,165,62,56,2,0,54,0,3.757576,33.939394
5,467270,176,50,50,0,0,50,0,2.840909,28.409091
2,326611,149,43,37,2,0,35,0,2.885906,24.832215
9,688393,86,27,27,0,0,27,0,3.139535,31.395349

In [57]:

# Overall baseline
overall_ter_rate = df_clean["flag_ter_below_1"].mean() * 100
overall_warning_rate = df_clean["any_warning"].mean() * 100

print(f"Overall TER < 1 rate: {overall_ter_rate:.2f}%")
print(f"Overall any-warning rate: {overall_warning_rate:.2f}%")

# Compare repeat users with the overall baseline
repeat_user_summary = user_risk[user_risk["total_tasks"] > 1].copy()

repeat_user_summary["ter_below_1_rate_pct"] = (
    repeat_user_summary["ter_below_1_tasks"]
    / repeat_user_summary["total_tasks"] * 100
)

repeat_user_summary["ter_rate_vs_overall"] = (
    repeat_user_summary["ter_below_1_rate_pct"] / overall_ter_rate
)

display(
    repeat_user_summary[
        [
            "user_id", "total_tasks", "ter_below_1_rate_pct",
            "ter_rate_vs_overall", "blank_tasks",
            "extreme_low_ter_tasks", "extreme_cps_tasks"
        ]
    ].sort_values("ter_rate_vs_overall", ascending=False)
)

Overall TER < 1 rate: 11.47%
Overall any-warning rate: 13.19%

,user_id,total_tasks,ter_below_1_rate_pct,ter_rate_vs_overall,blank_tasks,extreme_low_ter_tasks,extreme_cps_tasks
7,632098,165,32.727273,2.853538,2,0,0
9,688393,86,31.395349,2.737406,0,0,0
1,311760,184,30.978261,2.701039,0,0,0
4,410566,349,30.085960,2.623238,0,0,0
5,467270,176,28.409091,2.477030,0,0,0
8,681509,358,27.653631,2.411160,1,0,0
6,580062,609,26.929392,2.348013,7,0,0
0,222099,333,26.726727,2.330342,0,0,0
3,393886,509,24.165029,2.106984,4,0,0
2,326611,149,23.489933,2.048121,2,0,0

In [58]:

# Inspect tasks with TER < 1 for the 10 repeat users
repeat_ids = user_risk.loc[
    user_risk["total_tasks"] > 1, "user_id"
]

review_cols = [
    "user_id",
    "duration_clean",
    "task_time_clean",
    "ter",
    "analysis_char_count",
    "user_text",
    "whisper_text",
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_extreme_cps"
]

fast_tasks = df_clean[
    df_clean["user_id"].isin(repeat_ids)
    & df_clean["flag_ter_below_1"]
][review_cols].copy()

display(fast_tasks.head(30))

,user_id,duration_clean,task_time_clean,ter,analysis_char_count,user_text,whisper_text,flag_blank_submission,flag_extreme_low_ter,flag_extreme_cps
48865,580062,8.22,7.0,0.851582,6,ओके ओके,ओके ओके,False,False,False
48867,580062,12.66,4.0,0.315956,106,नहीं वो तो मुझे तो ध्यान है। नहीं मैंने तो ऐसे...,नहीं वो तो मुझे तो ध्यान है। नहीं मैंने तो ऐसे...,False,False,False
48869,580062,6.96,5.0,0.718391,51,आप अच्छे जगह पर जाइए जहां कनेक्शन अच्छा हो आपक...,आप अच्छे जगह पर जाए जहां कनेक्शन अच्छा हो आपका...,False,False,False
48871,580062,13.38,5.0,0.373692,129,वो चल रहा है प्रदान मंत्री आवास योजना तो मतलब ...,प्रदान मंत्री आवास एजना तो मतलब हर जो अठार साल...,False,False,False
48872,688393,10.02,6.0,0.598802,141,इन्वेस्ट करने घर को सजाने में किस तरीके से खर्...,इन्वेस्ट करने घर को सजाने में किस तरीके से खर्...,False,False,False
48875,688393,9.99,5.0,0.500501,75,ओके ओके मैं भी न्यू कमा रहा हूँ कोई कोई डर स...,तो धन्यवाद,False,False,False
48877,393886,9.69,5.0,0.515996,103,आच्छा आच्छा यहाँ पर सर अभी दो दिनों से बारीस ह...,यहाँ पर सर अभी दो दिनों से बारीस हो रही है सर ...,False,False,False
48880,393886,13.20,11.0,0.833333,153,ऐन टाइम पर जो हमने तय किया तो पास बिल्कुल भी...,"आप पास की टेंशन मत लो, आप केवल त्यार होके आजो ...",False,False,False
48881,580062,8.61,8.0,0.929152,95,कि तिलवाना और कुछ मजार जन होते हैं जो बच्चों क...,कि दिल्वाना और कुछ-कुछ मजार जन होते हैं जो बच्...,False,False,False
48889,393886,8.07,8.0,0.991326,44,एक सेकेंड सर मैं देखता हूँ अच्छा दोस्तों के नए...,एक साइन से मैं देखता हूँ अच्छा दोस्तों के नई श...,False,False,False
48894,393886,11.28,5.0,0.443262,161,"मुझे दूसरा स्कूल जब चेंज हुआ, वहाँ पे इतने अच्...","मुझे दूसरा स्कूल जब चेंज हुआ, वहाँ पर इतने अच्...",False,False,False
48895,632098,8.19,5.0,0.610501,85,जी जी जी लगता था जब सारे दोस्त साथ में होते थे...,जी जी जी लगता था जब सारे दोस्त साथ में होते थे...,False,False,False
48896,688393,10.56,10.0,0.946970,85,और उनके जो मित्र थे कवि कलश तो उन्होंने जो लास...,उनके मित्र थे कभी कलश तो उन्होंने जो लास्ट जो ...,False,False,False
48898,393886,9.15,5.0,0.546448,108,हाँ अब आवाजें जो दिन में तो बहुत अच्छी लगती है...,अब आजे जो दिन में तो बहुत अच्छी लगती है जैसे प...,False,False,False
48900,393886,13.29,8.0,0.601956,162,उस जमाने में भी बहुत चली है और आज कल काफी लोग...,जमान में भी बहुत चली है और आज कल काफी लोग देखत...,False,False,False
48902,688393,9.09,5.0,0.550055,93,कहीं एक्सीडेंट हो गया था वह उसे एक्सीडेंट कोई ...,कहीं एक्सीडेंट हो गया था वह उसे एक्सीडेंट कोई ...,False,False,False
48909,393886,10.95,6.0,0.547945,123,जनरेशन ही ऐसा आने वाला है कि उसमें कोई कुछ नही...,जनरेशन ही ऐसा आने वाला है कि उसमें कोई कुछ नही...,False,False,False
48911,688393,12.74,6.0,0.470958,105,बट उन्होंने जिस टाइप के गाने लिखे है ना वो अभी...,बट उन्होंने जिस टाइप के गाने लिखे है ना वो अभी...,False,False,False
48913,393886,4.02,4.0,0.995025,42,"हां, वहाँ पर सिगरेट उग्रेट पीना, वो सबका मजा अ...","हाँ, वहाँ पर सिगरेट उग्रेट पीना, वो सबका माझा ...",False,False,False
48917,393886,13.29,8.0,0.601956,159,"उसको complete करें, उसके बाद other work में ध्...","उसको complete करें, उसके बाद other work में ध्...",False,False,False
48919,393886,11.91,8.0,0.671704,83,सर्टिफिकेट तक गई और मैं नेशनल लवले कैम्प वहा...,जो आपने देखा होगा वगैरह होती है तो तो,False,False,False
48921,688393,12.39,12.0,0.968523,152,जी तो आपने मतलब जैसे NCC के कैम में पार्टिसिपे...,जी तो आपने मतलब जैसे NCC के कैम में पार्टिसिपे...,False,False,False
48924,393886,11.52,5.0,0.434028,90,लुटे लेकर पार्टी कर लोग से पार्टी तो मैंने बहु...,लुटे लेकर पार्टी कर लोग से पार्टी तो मैंने बहु...,False,False,False
48925,393886,7.62,6.0,0.787402,107,पर यह सीज़े ना आपस में सब जुड़ जाता है गनू मत...,पर यह सीज़े ना अपस में सब जुड़ जाता है गनू मतल...,False,False,False
48926,688393,14.35,9.0,0.627178,137,"अच्छा एक तरह की दाल होती है, उसकी कचोड़ी, हाँ,...","अच्छा एक तरह की दाल होती है, उसकी कचोड़ी, हाँ,...",False,False,False
48927,688393,11.01,5.0,0.454133,124,सर जो भी टॉपिक था उस टॉपिक बताया जाता था वह पू...,पुरक नहीं लेते थे तेज टॉपिक बता देते थे पूछते ...,False,False,False
48929,393886,12.42,4.0,0.322061,112,हाँ जी वह बॉल नहीं वो पत्थर से सारे गिर जाते ह...,बॉल नहीं वो पत्थर से सारे गिर जाते हैं तो फिर ...,False,False,False
48932,688393,9.63,6.0,0.623053,76,जी आह मैडम मतलब जो भी है अपने भारत के अंदर बहु...,जी आप मैंने बारत कंदर बहुत साइड जगह से जो मतलब...,False,False,False
48938,393886,10.62,10.0,0.941620,81,तो उसका जस्ट टैन की नॉर्मल ही नाम रख दिया था ह...,तो उसका जस्ट टैन की नॉर्मल ही नाम रख दिया था ह...,False,False,False
48946,688393,9.17,8.0,0.872410,40,हम्म अगला अ क्या है संस्कृतिक नृत्य करते हैं...,अगला संस्कृतिक नृत्य करते हैं क्या,False,False,False

In [59]:

from difflib import SequenceMatcher

def text_similarity(user_text, whisper_text):
    if not isinstance(user_text, str) or not isinstance(whisper_text, str):
        return None
    if not whisper_text.strip():
        return None

    user_text = " ".join(user_text.split())
    whisper_text = " ".join(whisper_text.split())

    return SequenceMatcher(None, user_text, whisper_text).ratio()

fast_tasks["whisper_similarity"] = fast_tasks.apply(
    lambda row: text_similarity(row["user_text"], row["whisper_text"]),
    axis=1
)

fast_tasks["whisper_difference_rate"] = (
    1 - fast_tasks["whisper_similarity"]
)

display(
    fast_tasks[
        [
            "user_id", "ter", "whisper_similarity",
            "whisper_difference_rate", "user_text", "whisper_text"
        ]
    ].sort_values("whisper_difference_rate", ascending=False).head(20)
)

,user_id,ter,whisper_similarity,whisper_difference_rate,user_text,whisper_text
51287,467270,0.738552,0.000000,1.000000,Inaudible,अजय को
51333,467270,0.959233,0.000000,1.000000,Inaudible,प्रभावित प्रभावित
51003,580062,0.990099,0.000000,1.000000,ब्लैंक,प्रति प्रति प्रति प्रति प्रति प्रति प्रति प्रत...
49622,222099,0.934579,0.012793,0.987207,तो उसमें तो ऐसा है ना कि महसूस तो मुझे बहुत गल...,मैंने मैसूस की बहुत सामात रह था। मुझे आराजित ह...
51092,681509,0.442478,0.012903,0.987097,ठीक है आपको कोई खास मठ आता है नहीं आता है आप अ...,जी
49199,393886,0.355240,0.065574,0.934426,चाहे वे कितना भी आए वे में उसे सामना चीज़ नह...,प्यास्य।
51559,393886,0.439560,0.083682,0.916318,उन्होंने बोला कोई नहीं है आपका घर यहां से दूर...,उच्य अ अ अचा
51179,681509,0.387597,0.086957,0.913043,आप वह लोग भी जानते थे जो लोग निकालते थे वह लोग...,"अगर रो दी,"
51206,681509,0.486449,0.089888,0.910112,वडा पाव मुझे स्ट्रीट फूड ज्यादा पसंद है हाउ मा...,वाड़ा पाहो
51191,681509,0.737101,0.094118,0.905882,मुझे उतारने के लिए बिल्कुल नहीं कहा पर मैं उतर...,अगर यहां को
49487,222099,0.840336,0.107143,0.892857,कॉलेज,प्रति लोगों को बोलना भी उनको सही नहीं है वह जो...
49239,222099,0.568182,0.114537,0.885463,अ........पहले अप..विश्व अंधविश्वास बहुत सारा ह...,अब अब अब अब अब अब अब अब अब अब अब अब अब अब अब अ...
50693,410566,0.641026,0.130653,0.869347,उनको अच्छा लग रहा है अच्छा फील हो रहा है एनर्ज...,अपने अपने अपने अपने
49873,580062,0.492207,0.134021,0.865979,तो ये होता हे ढाबों में ओर हा अगर ढाबों मै जा...,सब्सक्राइब करें और जय करें और
51104,681509,0.380518,0.142857,0.857143,सिटीज में जितना क्लाउड रहेगा ना मोस्टली महाराष...,राज्यान को पहले बहुत खुद प्रभावी नहीं है।
50404,410566,0.493827,0.142857,0.857143,वो तो लाइफ होती है वह टेंशन फ्री होती है कोई ट...,दिना जाऊंगी आपको नहीं
49945,467270,0.913242,0.148148,0.851852,Inaudible जी inaudible जी,जी
49317,580062,0.653595,0.148148,0.851852,हम लोग ऐसा है कि पेंटिंग बनाने के लिए सोचे पैं...,हम पुभीभ प पूछुप
49570,222099,0.415369,0.150000,0.850000,हां! शो पीस आर्टिस्ट तो नहीं है।,नहाल झाल
50668,410566,0.483092,0.150538,0.849462,मुझे मेम ऐसे ही ch महीने हो ज्यादा बर्क नहीं क...,"मैंने ज्यादा बर्क नहीं किया, मैं पढ़ाई के साथ ..."

In [60]:

# Add Whisper similarity to all tasks for the repeat users
repeat_ids = user_risk.loc[
    user_risk["total_tasks"] > 1, "user_id"
]

df_clean["whisper_similarity"] = df_clean.apply(
    lambda row: text_similarity(row["user_text"], row["whisper_text"]),
    axis=1
)

df_clean["flag_low_whisper_similarity"] = (
    df_clean["whisper_similarity"].notna()
    & (df_clean["whisper_similarity"] < 0.20)
)

repeat_quality_summary = (
    df_clean[df_clean["user_id"].isin(repeat_ids)]
    .groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        low_similarity_tasks=("flag_low_whisper_similarity", "sum"),
        blank_tasks=("flag_blank_submission", "sum"),
        ter_below_1_tasks=("flag_ter_below_1", "sum"),
        extreme_low_ter_tasks=("flag_extreme_low_ter", "sum"),
        extreme_cps_tasks=("flag_extreme_cps", "sum")
    )
    .reset_index()
)

repeat_quality_summary["low_similarity_rate_pct"] = (
    repeat_quality_summary["low_similarity_tasks"]
    / repeat_quality_summary["total_tasks"] * 100
)

display(
    repeat_quality_summary.sort_values(
        "low_similarity_rate_pct", ascending=False
    )
)

,user_id,total_tasks,low_similarity_tasks,blank_tasks,ter_below_1_tasks,extreme_low_ter_tasks,extreme_cps_tasks,low_similarity_rate_pct
5,467270,176,13,0,50,0,0,7.386364
8,681509,358,22,1,99,0,0,6.145251
9,688393,86,4,0,27,0,0,4.651163
3,393886,509,21,4,123,0,0,4.125737
2,326611,149,6,2,35,0,0,4.026846
0,222099,333,13,0,89,0,0,3.903904
6,580062,609,21,7,164,0,0,3.448276
4,410566,349,10,0,105,0,0,2.865330
1,311760,184,4,0,57,0,0,2.173913
7,632098,165,3,2,54,0,0,1.818182

In [61]:

# Check overlap between low Whisper similarity and existing warnings
review_cols = [
    "flag_blank_submission",
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps",
    "flag_low_whisper_similarity"
]

print("Warning overlap matrix:")
display(
    df_clean[review_cols].astype(int).T.dot(
        df_clean[review_cols].astype(int)
    )
)

# Tasks with low similarity AND at least one existing warning
df_clean["flag_combined_review"] = (
    df_clean["flag_low_whisper_similarity"]
    & df_clean[
        [
            "flag_blank_submission",
            "flag_extreme_low_ter",
            "flag_ter_below_1",
            "flag_extreme_cps"
        ]
    ].any(axis=1)
)

print(
    "\nTasks with low similarity plus another warning:",
    int(df_clean["flag_combined_review"].sum())
)

display(
    df_clean.loc[
        df_clean["flag_combined_review"],
        [
            "user_id", "duration_clean", "task_time_clean", "ter",
            "user_text", "whisper_text"
        ]
    ].head(20)
)

Warning overlap matrix:

,flag_blank_submission,flag_extreme_low_ter,flag_ter_below_1,flag_extreme_cps,flag_low_whisper_similarity
flag_blank_submission,1019,0,126,0,1019
flag_extreme_low_ter,0,517,517,346,0
flag_ter_below_1,126,517,5939,457,155
flag_extreme_cps,0,346,457,457,0
flag_low_whisper_similarity,1019,0,155,0,2018

Tasks with low similarity plus another warning: 1048

,user_id,duration_clean,task_time_clean,ter,user_text,whisper_text
142,73636811,1.23,11.65,9.471545,[blank],प्रस्तुति प्रस्तुति
434,71420491,2.13,8.94,4.197183,[blank],पूर्ट पर दिया वाला से जिन्ने पर यह नहीं रखेगा
532,71716111,1.65,4.69,2.842424,[blank],अच्छा अच्छा
591,72370108,1.26,9.15,7.261905,[blank],सुभाग
616,72464859,1.08,5.65,5.231481,[blank],प्रस्तुति प्रस्तुति
630,74986272,2.00,10.22,5.110000,[blank],लेकिन चोटी बच्चो को
741,71126366,1.02,11.17,10.950980,[blank],प्रस्तुति प्रस्तुति
924,71356775,1.53,10.93,7.143791,[blank],प्रस्तुति प्रस्तुति
1134,71958800,1.14,4.26,3.736842,[blank],झाल
1146,72179550,1.11,258.48,232.864865,[blank],झाल
1190,73415368,1.05,8.35,7.952381,[blank],झाल
1216,72945618,1.89,8.45,4.470899,[blank],"हाँ, हाँ, ब्लैक सिट्स"
1226,72945915,1.47,6.97,4.741497,[blank],अंडीडी जी
1230,72945301,1.41,4.93,3.496454,[blank],कर दो
1272,73644901,1.32,5.15,3.901515,[blank],जिनने आज हम गुर्शिन है
1393,71356141,1.20,2.60,2.166667,[blank],झाल
1422,71356386,1.47,2.93,1.993197,[blank],कर दो
1558,71479680,1.05,2.52,2.400000,[blank],झाल
1607,71487740,2.97,3.93,1.323232,[blank],हुआ है
1659,71539031,1.05,2.85,2.714286,[blank],प्रश्नात्र प्रश्नात्र

In [62]:

# Low Whisper similarity, excluding blank/empty submissions
df_clean["flag_low_similarity_nonblank"] = (
    df_clean["flag_low_whisper_similarity"]
    & ~df_clean["is_blank_only_submission"]
    & ~df_clean["is_empty_submission"]
)

print(
    "Low-similarity tasks excluding blank/empty:",
    int(df_clean["flag_low_similarity_nonblank"].sum())
)

# Among these, count tasks that also have a timing/CPS warning
timing_flags = [
    "flag_extreme_low_ter",
    "flag_ter_below_1",
    "flag_extreme_cps"
]

df_clean["flag_nonblank_similarity_plus_timing"] = (
    df_clean["flag_low_similarity_nonblank"]
    & df_clean[timing_flags].any(axis=1)
)

print(
    "Nonblank low-similarity tasks with timing/CPS warning:",
    int(df_clean["flag_nonblank_similarity_plus_timing"].sum())
)

display(
    df_clean.loc[
        df_clean["flag_nonblank_similarity_plus_timing"],
        [
            "user_id", "duration_clean", "task_time_clean", "ter",
            "user_text", "whisper_text"
        ]
    ].head(20)
)

Low-similarity tasks excluding blank/empty: 992
Nonblank low-similarity tasks with timing/CPS warning: 29

,user_id,duration_clean,task_time_clean,ter,user_text,whisper_text
6026,72033827,13.23,8.84,0.668178,है,दिचय न की अनम कितव केंद्र मन
8934,72663496,11.61,9.89,0.851852,नॉइस,अब आपको प्रशान देखें
15414,72758874,11.97,6.61,0.552214,तो,�.
34455,72573373,7.17,6.85,0.955370,आज करेंगेबाद हमें यह बताया है तो हम सभी ने से...,आज करेंगे
43471,71040227,7.83,6.11,0.780332,blankblank,अजय को
48875,688393,9.99,5.00,0.500501,ओके ओके मैं भी न्यू कमा रहा हूँ कोई कोई डर स...,तो धन्यवाद
49039,580062,11.49,8.00,0.696258,पर आई डी करे रहे हैं और हमलोग जाए तो हमसे मतलब...,और हमारे टॉपिक तो
49199,393886,11.26,4.00,0.355240,चाहे वे कितना भी आए वे में उसे सामना चीज़ नह...,प्यास्य।
49239,222099,12.32,7.00,0.568182,अ........पहले अप..विश्व अंधविश्वास बहुत सारा ह...,अब अब अब अब अब अब अब अब अब अब अब अब अब अब अब अ...
49317,580062,10.71,7.00,0.653595,हम लोग ऐसा है कि पेंटिंग बनाने के लिए सोचे पैं...,हम पुभीभ प पूछुप
49487,222099,11.90,10.00,0.840336,कॉलेज,प्रति लोगों को बोलना भी उनको सही नहीं है वह जो...
49570,222099,9.63,4.00,0.415369,हां! शो पीस आर्टिस्ट तो नहीं है।,नहाल झाल
49622,222099,12.84,12.00,0.934579,तो उसमें तो ऐसा है ना कि महसूस तो मुझे बहुत गल...,मैंने मैसूस की बहुत सामात रह था। मुझे आराजित ह...
49873,580062,12.19,6.00,0.492207,तो ये होता हे ढाबों में ओर हा अगर ढाबों मै जा...,सब्सक्राइब करें और जय करें और
49945,467270,10.95,10.00,0.913242,Inaudible जी inaudible जी,जी
50404,410566,12.15,6.00,0.493827,वो तो लाइफ होती है वह टेंशन फ्री होती है कोई ट...,दिना जाऊंगी आपको नहीं
50668,410566,12.42,6.00,0.483092,मुझे मेम ऐसे ही ch महीने हो ज्यादा बर्क नहीं क...,"मैंने ज्यादा बर्क नहीं किया, मैं पढ़ाई के साथ ..."
50693,410566,10.92,7.00,0.641026,उनको अच्छा लग रहा है अच्छा फील हो रहा है एनर्ज...,अपने अपने अपने अपने
51003,580062,6.06,6.00,0.990099,ब्लैंक,प्रति प्रति प्रति प्रति प्रति प्रति प्रति प्रत...
51092,681509,13.56,6.00,0.442478,ठीक है आपको कोई खास मठ आता है नहीं आता है आप अ...,जी

In [63]:

user_review_summary = (
    df_clean.groupby("user_id")
    .agg(
        total_tasks=("user_id", "size"),
        suspicious_nonblank_tasks=(
            "flag_nonblank_similarity_plus_timing", "sum"
        ),
        blank_tasks=("flag_blank_submission", "sum"),
        tasks_with_any_warning=("any_warning", "sum")
    )
    .reset_index()
)

user_review_summary = user_review_summary[
    user_review_summary["suspicious_nonblank_tasks"] > 0
].sort_values(
    ["suspicious_nonblank_tasks", "total_tasks"],
    ascending=False
)

display(user_review_summary.head(20))

,user_id,total_tasks,suspicious_nonblank_tasks,blank_tasks,tasks_with_any_warning
8,681509,358,6,1,100
6,580062,609,4,7,171
0,222099,333,4,0,89
5,467270,176,4,0,50
4,410566,349,3,0,105
3,393886,509,2,4,127
9,688393,86,1,0,27
4540,71040227,1,1,0,1
21715,72033827,1,1,0,1
29231,72573373,1,1,0,1
30585,72663496,1,1,0,1
32358,72758874,1,1,0,1

In [64]:
df_clean["task_risk_score"] = (
    4 * df_clean["flag_blank_submission"].astype(int)
    + 3 * df_clean["flag_extreme_low_ter"].astype(int)
    + (
        df_clean["flag_ter_below_1"]
        & ~df_clean["flag_extreme_low_ter"]
    ).astype(int)
    + 2 * df_clean["flag_extreme_cps"].astype(int)
)

user_risk = df_clean.groupby("user_id").agg(
    total_tasks=("user_id", "size"),
    total_risk_score=("task_risk_score", "sum")
).reset_index()

user_risk["risk_percentage"] = (
    user_risk["total_risk_score"]
    / (10 * user_risk["total_tasks"])
    * 100
)

user_risk = user_risk.sort_values(
    "risk_percentage", ascending=False
)

display(user_risk)

        user_id  total_tasks  total_risk_score  risk_percentage
36846  73178811            1                 5             50.0
36863  73179045            1                 5             50.0
36918  73179645            1                 5             50.0
37771  73190638            1                 5             50.0
37849  73191519            1                 5             50.0
...         ...          ...               ...              ...
26     56568700            1                 0              0.0
25     56568674            1                 0              0.0
24     56568666            1                 0              0.0
23     56568610            1                 0              0.0
43514  73636549            1                 0              0.0

[48875 rows x 4 columns]

In [65]:
import numpy as np

# Maximum possible task score = 9
user_risk = df_clean.groupby("user_id").agg(
    total_tasks=("user_id", "size"),
    total_risk_score=("task_risk_score", "sum"),
    flagged_tasks=("any_warning", "sum")
).reset_index()

# Normalized weighted risk percentage
user_risk["risk_percentage"] = (
    user_risk["total_risk_score"]
    / (9 * user_risk["total_tasks"])
    * 100
)

# Review priority: a single task is not enough to establish a pattern
user_risk["review_priority"] = np.select(
    [
        (user_risk["total_tasks"] >= 5) &
        (user_risk["flagged_tasks"] >= 3),

        user_risk["flagged_tasks"] >= 2
    ],
    [
        "High-priority review",
        "Review"
    ],
    default="Insufficient history"
)

user_risk = user_risk.sort_values(
    ["review_priority", "risk_percentage"],
    ascending=[True, False]
)

display(user_risk)

,user_id,total_tasks,total_risk_score,flagged_tasks,risk_percentage,review_priority
7,632098,165,62,56,4.175084,High-priority review
6,580062,609,192,171,3.503010,High-priority review
9,688393,86,27,27,3.488372,High-priority review
1,311760,184,57,57,3.442029,High-priority review
4,410566,349,105,105,3.342884,High-priority review
...,...,...,...,...,...,...
48870,75315875,1,0,0,0.000000,Insufficient history
48871,75319972,1,0,0,0.000000,Insufficient history
48872,75325959,1,0,0,0.000000,Insufficient history
48873,75325974,1,0,0,0.000000,Insufficient history
48874,75326070,1,0,0,0.000000,Insufficient history

In [66]:
# Show the 10 users with the most flagged tasks
display(
    user_risk.sort_values(
        ["flagged_tasks", "total_risk_score"],
        ascending=False
    ).head(10)
)

,user_id,total_tasks,total_risk_score,flagged_tasks,risk_percentage,review_priority
6,580062,609,192,171,3.503010,High-priority review
3,393886,509,139,127,3.034272,High-priority review
4,410566,349,105,105,3.342884,High-priority review
8,681509,358,103,100,3.196772,High-priority review
0,222099,333,89,89,2.969636,High-priority review
1,311760,184,57,57,3.442029,High-priority review
7,632098,165,62,56,4.175084,High-priority review
5,467270,176,50,50,3.156566,High-priority review
2,326611,149,43,37,3.206562,High-priority review
9,688393,86,27,27,3.488372,High-priority review

In [ ]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("transcription_data.csv")

# Clean numeric columns
df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

# Text cleanup
text = df["user_text"].fillna("").astype(str).str.strip()
whisper = df["whisper_text"].fillna("").astype(str).str.strip()

# Character count: ignore whitespace and the [blank] marker
df["char_count"] = text.apply(
    lambda x: 0 if x.lower() in ("", "[blank]")
    else sum(not c.isspace() for c in x)
)

# Task-level signals
df["ter"] = df["time_taken_by_user"] / df["duration"]
df["cps"] = df["char_count"] / df["time_taken_by_user"].replace(0, np.nan)

df["blank_flag"] = (
    text.str.lower().isin(["", "[blank]"])
    & (whisper != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < 0.1787571047)
    & (df["duration"] > 1)
)

df["high_cps_flag"] = (
    (df["cps"] > 59.858)
    & (df["duration"] > 5)
)

# Transcriber-level rates
# Denominators use eligible tasks for each signal.
df["ter_eligible"] = (
    df["duration"] > 1
) & df["ter"].notna()

df["cps_eligible"] = (
    (df["duration"] > 5)
    & (df["time_taken_by_user"] > 0)
    & df["cps"].notna()
)

users = df.groupby("user_id").agg(
    total_tasks=("user_id", "size"),
    blank_tasks=("blank_flag", "sum"),
    ter_eligible_tasks=("ter_eligible", "sum"),
    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    cps_eligible_tasks=("cps_eligible", "sum"),
    high_cps_tasks=("high_cps_flag", "sum")
)

users["blank_rate"] = (
    100 * users["blank_tasks"] / users["total_tasks"]
)

users["extreme_ter_rate"] = (
    100 * users["extreme_ter_tasks"]
    / users["ter_eligible_tasks"].replace(0, np.nan)
)

users["high_cps_rate"] = (
    100 * users["high_cps_tasks"]
    / users["cps_eligible_tasks"].replace(0, np.nan)
)

# Calculate thresholds using repeat transcribers with >=20 tasks
eligible_users = users[users["total_tasks"] >= 20].copy()

thresholds = eligible_users[
    ["blank_rate", "extreme_ter_rate", "high_cps_rate"]
].quantile(0.95)

print("95th percentile thresholds (%):")
print(thresholds.round(2))

# Apply AND-based blocking rule
users["block_candidate"] = (
    (users["total_tasks"] >= 20)
    & (users["blank_rate"] > thresholds["blank_rate"])
    & (users["extreme_ter_rate"] > thresholds["extreme_ter_rate"])
    & (users["high_cps_rate"] > thresholds["high_cps_rate"])
)

# Show repeat transcribers ranked by suspicious rates
result = users[users["total_tasks"] >= 20].sort_values(
    ["block_candidate", "extreme_ter_rate"],
    ascending=[False, False]
)

print("\nTranscriber-level results:")
display(result.round(2))import pandas as pd
import numpy as np

# ==========================================
# 1. LOAD DATASET
# ==========================================
df = pd.read_csv("../data/raw/transcription_data.csv")

df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

print("Dataset loaded:", df.shape)
print("Unique transcribers:", df["user_id"].nunique())


# ==========================================
# 2. CLEAN TEXT AND CALCULATE METRICS
# ==========================================
text = df["user_text"].fillna("").astype(str).str.strip()
whisper = df["whisper_text"].fillna("").astype(str).str.strip()

# Count non-whitespace characters; exclude [blank] marker
df["char_count"] = text.apply(
    lambda x: 0 if x.lower() in ("", "[blank]")
    else sum(not c.isspace() for c in x)
)

df["ter"] = (
    df["time_taken_by_user"]
    / df["duration"].where(df["duration"] > 0)
)

df["cps"] = (
    df["char_count"]
    / df["time_taken_by_user"].where(df["time_taken_by_user"] > 0)
)


# ==========================================
# 3. DEFINE WARNING SIGNALS
# ==========================================
df["blank_flag"] = (
    text.str.lower().isin(["", "[blank]"])
    & (whisper != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < 0.1787571047)
    & (df["duration"] > 1)
)

df["high_cps_flag"] = (
    (df["cps"] > 59.858)
    & (df["duration"] > 5)
)


# ==========================================
# 4. DEFINE ELIGIBLE TASKS FOR EACH RATE
# ==========================================
df["blank_eligible"] = (
    (df["duration"] > 1)
    & (whisper != "")
)

df["ter_eligible"] = (
    (df["duration"] > 1)
    & df["ter"].notna()
)

df["cps_eligible"] = (
    (df["duration"] > 5)
    & (df["time_taken_by_user"] > 0)
    & df["cps"].notna()
)


# ==========================================
# 5. AGGREGATE AT TRANSCRIBER LEVEL
# ==========================================
users = df.groupby("user_id").agg(
    total_tasks=("user_id", "size"),

    blank_tasks=("blank_flag", "sum"),
    blank_eligible_tasks=("blank_eligible", "sum"),

    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    ter_eligible_tasks=("ter_eligible", "sum"),

    high_cps_tasks=("high_cps_flag", "sum"),
    cps_eligible_tasks=("cps_eligible", "sum")
)

# Rates as percentages
users["blank_rate"] = (
    100 * users["blank_tasks"]
    / users["blank_eligible_tasks"].replace(0, np.nan)
)

users["extreme_ter_rate"] = (
    100 * users["extreme_ter_tasks"]
    / users["ter_eligible_tasks"].replace(0, np.nan)
)

users["high_cps_rate"] = (
    100 * users["high_cps_tasks"]
    / users["cps_eligible_tasks"].replace(0, np.nan)
)


# ==========================================
# 6. CALCULATE DATA-DRIVEN THRESHOLDS
# ==========================================
# Use repeat transcribers with at least 20 tasks
eligible_users = users[users["total_tasks"] >= 20].copy()

if len(eligible_users) < 2:
    raise ValueError(
        "Not enough transcribers with at least 20 tasks "
        "to calculate meaningful percentile thresholds."
    )

thresholds = eligible_users[
    ["blank_rate", "extreme_ter_rate", "high_cps_rate"]
].quantile(0.95)

print("\n========== 95TH PERCENTILE THRESHOLDS ==========")
print(thresholds.round(2).to_string())

print("\nTranscribers used to calculate thresholds:",
      len(eligible_users))


# ==========================================
# 7. APPLY AND-BASED BLOCKING RULE
# ==========================================
users["block_candidate"] = (
    (users["total_tasks"] >= 20)

    & users["blank_rate"].notna()
    & users["extreme_ter_rate"].notna()
    & users["high_cps_rate"].notna()

    & (users["blank_rate"] > thresholds["blank_rate"])
    & (users["extreme_ter_rate"] > thresholds["extreme_ter_rate"])
    & (users["high_cps_rate"] > thresholds["high_cps_rate"])
)


# ==========================================
# 8. DISPLAY RESULTS
# ==========================================
result = (
    users[users["total_tasks"] >= 20]
    .sort_values(
        ["block_candidate", "blank_rate", "extreme_ter_rate"],
        ascending=[False, False, False]
    )
)

columns_to_show = [
    "total_tasks",
    "blank_tasks",
    "blank_rate",
    "extreme_ter_tasks",
    "extreme_ter_rate",
    "high_cps_tasks",
    "high_cps_rate",
    "block_candidate"
]

print("\n========== TRANSCRIBER-LEVEL RESULTS ==========")
display(result[columns_to_show].round(2))

print("\n========== BLOCK CANDIDATES ==========")
candidates = result[result["block_candidate"]]
display(candidates[columns_to_show].round(2))

print("\nTotal block candidates:", len(candidates))


# ==========================================
# 9. SAVE RESULTS
# ==========================================
from pathlib import Path

output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)
import pandas as pd
import numpy as np

# ==========================================
# 1. LOAD DATASET
# ==========================================
df = pd.read_csv("../data/raw/transcription_data.csv")

df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

print("Dataset loaded:", df.shape)
print("Unique transcribers:", df["user_id"].nunique())


# ==========================================
# 2. CLEAN TEXT AND CALCULATE METRICS
# ==========================================
text = df["user_text"].fillna("").astype(str).str.strip()
whisper = df["whisper_text"].fillna("").astype(str).str.strip()

# Count non-whitespace characters; exclude [blank] marker
df["char_count"] = text.apply(
    lambda x: 0 if x.lower() in ("", "[blank]")
    else sum(not c.isspace() for c in x)
)

df["ter"] = (
    df["time_taken_by_user"]
    / df["duration"].where(df["duration"] > 0)
)

df["cps"] = (
    df["char_count"]
    / df["time_taken_by_user"].where(df["time_taken_by_user"] > 0)
)


# ==========================================
# 3. DEFINE WARNING SIGNALS
# ====import pandas as pd
import numpy as np

# ==========================================
# 1. LOAD DATASET
# ==========================================
df = pd.read_csv("../data/raw/transcription_data.csv")

df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

print("Dataset loaded:", df.shape)
print("Unique transcribers:", df["user_id"].nunique())


# ==========================================
# 2. CLEAN TEXT AND CALCULATE METRICS
# ==========================================
text = df["user_text"].fillna("").astype(str).str.strip()
whisper = df["whisper_text"].fillna("").astype(str).str.strip()

# Count non-whitespace characters; exclude [blank] marker
df["char_count"] = text.apply(
    lambda x: 0 if x.lower() in ("", "[blank]")
    else sum(not c.isspace() for c in x)
)

df["ter"] = (
    df["time_taken_by_user"]
    / df["duration"].where(df["duration"] > 0)
)

df["cps"] = (
    df["char_count"]
    / df["time_taken_by_user"].where(df["time_taken_by_user"] > 0)
)


# ==========================================
# 3. DEFINE WARNING SIGNALS
# ==========================================
df["blank_flag"] = (
    text.str.lower().isin(["", "[blank]"])
    & (whisper != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < 0.1787571047)
    & (df["duration"] > 1)
)

df["high_cps_flag"] = (
    (df["cps"] > 59.858)
    & (df["duration"] > 5)
)


# ==========================================
# 4. DEFINE ELIGIBLE TASKS FOR EACH RATE
# ==========================================
df["blank_eligible"] = (
    (df["duration"] > 1)
    & (whisper != "")
)

df["ter_eligible"] = (
    (df["duration"] > 1)
    & df["ter"].notna()
)

df["cps_eligible"] = (
    (df["duration"] > 5)
    & (df["time_taken_by_user"] > 0)
    & df["cps"].notna()
)


# ==========================================
# 5. AGGREGATE AT TRANSCRIBER LEVEL
# ==========================================
users = df.groupby("user_id").agg(
    total_tasks=("user_id", "size"),

    blank_tasks=("blank_flag", "sum"),
    blank_eligible_tasks=("blank_eligible", "sum"),

    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    ter_eligible_tasks=("ter_eligible", "sum"),

    high_cps_tasks=("high_cps_flag", "sum"),
    cps_eligible_tasks=("cps_eligible", "sum")
)

# Rates as percentages
users["blank_rate"] = (
    100 * users["blank_tasks"]
    / users["blank_eligible_tasks"].replace(0, np.nan)
)

users["extreme_ter_rate"] = (
    100 * users["extreme_ter_tasks"]
    / users["ter_eligible_tasks"].replace(0, np.nan)
)

users["high_cps_rate"] = (
    100 * users["high_cps_tasks"]
    / users["cps_eligible_tasks"].replace(0, np.nan)
)


# ==========================================
# 6. CALCULATE DATA-DRIVEN THRESHOLDS
# ==========================================
# Use repeat transcribers with at least 20 tasks
eligible_users = users[users["total_tasks"] >= 20].copy()

if len(eligible_users) < 2:
    raise ValueError(
        "Not enough transcribers with at least 20 tasks "
        "to calculate meaningful percentile thresholds."
    )

thresholds = eligible_users[
    ["blank_rate", "extreme_ter_rate", "high_cps_rate"]
].quantile(0.95)

print("\n========== 95TH PERCENTILE THRESHOLDS ==========")
print(thresholds.round(2).to_string())

print("\nTranscribers used to calculate thresholds:",
      len(eligible_users))


# ==========================================
# 7. APPLY AND-BASED BLOCKING RULE
# ==========================================
users["block_candidate"] = (
    (users["total_tasks"] >= 20)

    & users["blank_rate"].notna()
    & users["extreme_ter_rate"].notna()
    & users["high_cps_rate"].notna()

    & (users["blank_rate"] > thresholds["blank_rate"])
    & (users["extreme_ter_rate"] > thresholds["extreme_ter_rate"])
    & (users["high_cps_rate"] > thresholds["high_cps_rate"])
)


# ==========================================
# 8. DISPLAY RESULTS
# ==========================================
result = (
    users[users["total_tasks"] >= 20]
    .sort_values(
        ["block_candidate", "blank_rate", "extreme_ter_rate"],
        ascending=[False, False, False]
    )
)

columns_to_show = [
    "total_tasks",
    "blank_tasks",
    "blank_rate",
    "extreme_ter_tasks",
    "extreme_ter_rate",
    "high_cps_tasks",
    "high_cps_rate",
    "block_candidate"
]

print("\n========== TRANSCRIBER-LEVEL RESULTS ==========")
display(result[columns_to_show].round(2))

print("\n========== BLOCK CANDIDATES ==========")
candidates = result[result["block_candidate"]]
display(candidates[columns_to_show].round(2))

print("\nTotal block candidates:", len(candidates))


# ==========================================
# 9. SAVE RESULTS
# ==========================================
from pathlib import Path

output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)

result[columns_to_show].to_csv(
    output_dir / "transcriber_threshold_analysis.csv"
)

thresholds.rename("threshold_percent").to_csv(
    output_dir / "warning_rate_thresholds.csv"
)

print("\nSaved files:")
print(output_dir / "transcriber_threshold_analysis.csv")
print(output_dir / "warning_rate_thresholds.csv")

df["cps_eligible"] = (
    (df["duration"] > 5)
    & (df["time_taken_by_user"] > 0)
    & df["cps"].notna()
)


# ==========================================
# 5. AGGREGATE AT TRANSCRIBER LEVEL
# ==========================================
users = df.groupby("user_id").agg(
    total_tasks=("user_id", "size"),

    blank_tasks=("blank_flag", "sum"),
    blank_eligible_tasks=("blank_eligible", "sum"),

    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    ter_eligible_tasks=("ter_eligible", "sum"),

    high_cps_tasks=("high_cps_flag", "sum"),
    cps_eligible_tasks=("cps_eligible", "sum")
)

# Rates as percentages
users["blank_rate"] = (
    100 * users["blank_tasks"]
    / users["blank_eligible_tasks"].replace(0, np.nan)
)

users["extreme_ter_rate"] = (
    100 * users["extreme_ter_tasks"]
    / users["ter_eligible_tasks"].replace(0, np.nan)
)

users["high_cps_rate"] = (
    100 * users["high_cps_tasks"]
    / users["cps_eligible_tasks"].replace(0, np.nan)
)


# ==========================================
# 6. CALCULATE DATA-DRIVEN THRESHOLDS
# ==========================================
# Use repeat transcribers with at least 20 tasks
eligible_users = users[users["total_tasks"] >= 20].copy()

if len(eligible_users) < 2:
    raise ValueError(
        "Not enough transcribers with at least 20 tasks "
        "to calculate meaningful percentile thresholds."
    )

thresholds = eligible_users[
    ["blank_rate", "extreme_ter_rate", "high_cps_rate"]
].quantile(0.95)

print("\n========== 95TH PERCENTILE THRESHOLDS ==========")
print(thresholds.round(2).to_string())

print("\nTranscribers used to calculate thresholds:",
      len(eligible_users))


# ==========================================
# 7. APPLY AND-BASED BLOCKING RULE
# ==========================================
users["block_candidate"] = (
    (users["total_tasks"] >= 20)

    & users["blank_rate"].notna()
    & users["extreme_ter_rate"].notna()
    & users["high_cps_rate"].notna()

    & (users["blank_rate"] > thresholds["blank_rate"])
    & (users["extreme_ter_rate"] > thresholds["extreme_ter_rate"])
    & (users["high_cps_rate"] > thresholds["high_cps_rate"])
)


# ==========================================
# 8. DISPLAY RESULTS
# ==========================================
result = (
    users[users["total_tasks"] >= 20]
    .sort_values(
        ["block_candidate", "blank_rate", "extreme_ter_rate"],
        ascending=[False, False, False]
    )
)

columns_to_show = [
    "total_tasks",
    "blank_tasks",
    "blank_rate",
    "extreme_ter_tasks",
    "extreme_ter_rate",
    "high_cps_tasks",
    "high_cps_rate",
    "block_candidate"
]

print("\n========== TRANSCRIBER-LEVEL RESULTS ==========")
display(result[columns_to_show].round(2))

print("\n========== BLOCK CANDIDATES ==========")
candidates = result[result["block_candidate"]]
display(candidates[columns_to_show].round(2))

print("\nTotal block candidates:", len(candidates))


# ==========================================
# 9. SAVE RESULTS
# ==========================================
from pathlib import Path

output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)

result[columns_to_show].to_csv(
    output_dir / "transcriber_threshold_analysis.csv"
)

thresholds.rename("threshold_percent").to_csv(
    output_dir / "warning_rate_thresholds.csv"
)

print("\nSaved files:")
print(output_dir / "transcriber_threshold_analysis.csv")
print(output_dir / "warning_rate_thresholds.csv")
result[columns_to_show].to_csv(
    output_dir / "transcriber_threshold_analysis.csv"
)

thresholds.rename("threshold_percent").to_csv(
    output_dir / "warning_rate_thresholds.csv"
)

print("\nSaved files:")
print(output_dir / "transcriber_threshold_analysis.csv")
print(output_dir / "warning_rate_thresholds.csv")

print("\nBlock candidates:")
display(result[result["block_candidate"]].round(2))

SyntaxError: invalid syntax (2642414118.py, line 103)

In [69]:
import pandas as pd
import numpy as np

# ==========================================
# 1. LOAD DATASET
# ==========================================
df = pd.read_csv("../data/raw/transcription_data.csv")

df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

print("Dataset loaded:", df.shape)
print("Unique transcribers:", df["user_id"].nunique())


# ==========================================
# 2. CLEAN TEXT AND CALCULATE METRICS
# ==========================================
text = df["user_text"].fillna("").astype(str).str.strip()
whisper = df["whisper_text"].fillna("").astype(str).str.strip()

# Count non-whitespace characters; exclude [blank] marker
df["char_count"] = text.apply(
    lambda x: 0 if x.lower() in ("", "[blank]")
    else sum(not c.isspace() for c in x)
)

df["ter"] = (
    df["time_taken_by_user"]
    / df["duration"].where(df["duration"] > 0)
)

df["cps"] = (
    df["char_count"]
    / df["time_taken_by_user"].where(df["time_taken_by_user"] > 0)
)


# ==========================================
# 3. DEFINE WARNING SIGNALS
# ==========================================
df["blank_flag"] = (
    text.str.lower().isin(["", "[blank]"])
    & (whisper != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < 0.1787571047)
    & (df["duration"] > 1)
)

df["high_cps_flag"] = (
    (df["cps"] > 59.858)
    & (df["duration"] > 5)
)


# ==========================================
# 4. DEFINE ELIGIBLE TASKS FOR EACH RATE
# ==========================================
df["blank_eligible"] = (
    (df["duration"] > 1)
    & (whisper != "")
)

df["ter_eligible"] = (
    (df["duration"] > 1)
    & df["ter"].notna()
)

df["cps_eligible"] = (
    (df["duration"] > 5)
    & (df["time_taken_by_user"] > 0)
    & df["cps"].notna()
)


# ==========================================
# 5. AGGREGATE AT TRANSCRIBER LEVEL
# ==========================================
users = df.groupby("user_id").agg(
    total_tasks=("user_id", "size"),

    blank_tasks=("blank_flag", "sum"),
    blank_eligible_tasks=("blank_eligible", "sum"),

    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    ter_eligible_tasks=("ter_eligible", "sum"),

    high_cps_tasks=("high_cps_flag", "sum"),
    cps_eligible_tasks=("cps_eligible", "sum")
)

# Rates as percentages
users["blank_rate"] = (
    100 * users["blank_tasks"]
    / users["blank_eligible_tasks"].replace(0, np.nan)
)

users["extreme_ter_rate"] = (
    100 * users["extreme_ter_tasks"]
    / users["ter_eligible_tasks"].replace(0, np.nan)
)

users["high_cps_rate"] = (
    100 * users["high_cps_tasks"]
    / users["cps_eligible_tasks"].replace(0, np.nan)
)


# ==========================================
# 6. CALCULATE DATA-DRIVEN THRESHOLDS
# ==========================================
# Use repeat transcribers with at least 20 tasks
eligible_users = users[users["total_tasks"] >= 20].copy()

if len(eligible_users) < 2:
    raise ValueError(
        "Not enough transcribers with at least 20 tasks "
        "to calculate meaningful percentile thresholds."
    )

thresholds = eligible_users[
    ["blank_rate", "extreme_ter_rate", "high_cps_rate"]
].quantile(0.95)

print("\n========== 95TH PERCENTILE THRESHOLDS ==========")
print(thresholds.round(2).to_string())

print("\nTranscribers used to calculate thresholds:",
      len(eligible_users))


# ==========================================
# 7. APPLY AND-BASED BLOCKING RULE
# ==========================================
users["block_candidate"] = (
    (users["total_tasks"] >= 20)

    & users["blank_rate"].notna()
    & users["extreme_ter_rate"].notna()
    & users["high_cps_rate"].notna()

    & (users["blank_rate"] > thresholds["blank_rate"])
    & (users["extreme_ter_rate"] > thresholds["extreme_ter_rate"])
    & (users["high_cps_rate"] > thresholds["high_cps_rate"])
)


# ==========================================
# 8. DISPLAY RESULTS
# ==========================================
result = (
    users[users["total_tasks"] >= 20]
    .sort_values(
        ["block_candidate", "blank_rate", "extreme_ter_rate"],
        ascending=[False, False, False]
    )
)

columns_to_show = [
    "total_tasks",
    "blank_tasks",
    "blank_rate",
    "extreme_ter_tasks",
    "extreme_ter_rate",
    "high_cps_tasks",
    "high_cps_rate",
    "block_candidate"
]

print("\n========== TRANSCRIBER-LEVEL RESULTS ==========")
display(result[columns_to_show].round(2))

print("\n========== BLOCK CANDIDATES ==========")
candidates = result[result["block_candidate"]]
display(candidates[columns_to_show].round(2))

print("\nTotal block candidates:", len(candidates))


# ==========================================
# 9. SAVE RESULTS
# ==========================================
from pathlib import Path

output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)

result[columns_to_show].to_csv(
    output_dir / "transcriber_threshold_analysis.csv"
)

thresholds.rename("threshold_percent").to_csv(
    output_dir / "warning_rate_thresholds.csv"
)

print("\nSaved files:")
print(output_dir / "transcriber_threshold_analysis.csv")
print(output_dir / "warning_rate_thresholds.csv")

Dataset loaded: (51783, 8)
Unique transcribers: 48875

========== 95TH PERCENTILE THRESHOLDS ==========
blank_rate          2.81
extreme_ter_rate    0.00
high_cps_rate       0.00

Transcribers used to calculate thresholds: 10

========== TRANSCRIBER-LEVEL RESULTS ==========

,total_tasks,blank_tasks,blank_rate,extreme_ter_tasks,extreme_ter_rate,high_cps_tasks,high_cps_rate,block_candidate
user_id,,,,,,,,
326611,149,2,3.28,0,0.0,0,0.0,False
580062,609,7,2.23,0,0.0,0,0.0,False
632098,165,2,2.22,0,0.0,0,0.0,False
393886,509,4,1.63,0,0.0,0,0.0,False
681509,358,1,0.53,0,0.0,0,0.0,False
222099,333,0,0.00,0,0.0,0,0.0,False
311760,184,0,0.00,0,0.0,0,0.0,False
410566,349,0,0.00,0,0.0,0,0.0,False
467270,176,0,0.00,0,0.0,0,0.0,False
688393,86,0,0.00,0,0.0,0,0.0,False

========== BLOCK CANDIDATES ==========

Empty DataFrame
Columns: [total_tasks, blank_tasks, blank_rate, extreme_ter_tasks, extreme_ter_rate, high_cps_tasks, high_cps_rate, block_candidate]
Index: []

Total block candidates: 0

Saved files:
..\outputs\transcriber_threshold_analysis.csv
..\outputs\warning_rate_thresholds.csv

In [70]:
# Add broader low-TER signal at transcriber level
df["ter_below_1_flag"] = (
    (df["ter"] < 1) & (df["duration"] > 1)
)

users["ter_below_1_tasks"] = (
    df.groupby("user_id")["ter_below_1_flag"].sum()
)

users["ter_below_1_rate"] = (
    100 * users["ter_below_1_tasks"]
    / df.groupby("user_id").size()
)

display(
    users[users["total_tasks"] >= 20][[
        "total_tasks",
        "blank_rate",
        "extreme_ter_rate",
        "high_cps_rate",
        "ter_below_1_rate"
    ]].sort_values("ter_below_1_rate", ascending=False).round(2)
)

,total_tasks,blank_rate,extreme_ter_rate,high_cps_rate,ter_below_1_rate
user_id,,,,,
632098,165,2.22,0.0,0.0,32.73
688393,86,0.00,0.0,0.0,31.40
311760,184,0.00,0.0,0.0,30.98
410566,349,0.00,0.0,0.0,30.09
467270,176,0.00,0.0,0.0,28.41
681509,358,0.53,0.0,0.0,27.65
580062,609,2.23,0.0,0.0,26.93
222099,333,0.00,0.0,0.0,26.73
393886,509,1.63,0.0,0.0,24.17
326611,149,3.28,0.0,0.0,23.49

In [71]:
import pandas as pd
import numpy as np
from pathlib import Path

# 1. Load dataset
df = pd.read_csv("../data/raw/transcription_data.csv")

df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

text = df["user_text"].fillna("").astype(str).str.strip()
whisper = df["whisper_text"].fillna("").astype(str).str.strip()

# 2. Calculate task-level metrics
df["ter"] = (
    df["time_taken_by_user"]
    / df["duration"].where(df["duration"] > 0)
)

df["char_count"] = text.apply(
    lambda x: 0 if x.lower() in ("", "[blank]")
    else sum(not c.isspace() for c in x)
)

df["cps"] = (
    df["char_count"]
    / df["time_taken_by_user"].where(
        df["time_taken_by_user"] > 0
    )
)

# 3. Define warning signals
df["blank_flag"] = (
    text.str.lower().isin(["", "[blank]"])
    & (whisper != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < 0.1787571047)
    & (df["duration"] > 1)
)

df["ter_below_1_flag"] = (
    (df["ter"] < 1)
    & (df["duration"] > 1)
)

df["high_cps_flag"] = (
    (df["cps"] > 59.858)
    & (df["duration"] > 5)
)

# 4. Define eligible tasks for each rate
df["blank_eligible"] = (
    (df["duration"] > 1)
    & (whisper != "")
)

df["ter_eligible"] = (
    (df["duration"] > 1)
    & df["ter"].notna()
)

df["cps_eligible"] = (
    (df["duration"] > 5)
    & (df["time_taken_by_user"] > 0)
    & df["cps"].notna()
)

# 5. Aggregate by transcriber
users = df.groupby("user_id").agg(
    total_tasks=("user_id", "size"),

    blank_tasks=("blank_flag", "sum"),
    blank_eligible=("blank_eligible", "sum"),

    ter_below_1_tasks=("ter_below_1_flag", "sum"),
    ter_eligible=("ter_eligible", "sum"),

    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    high_cps_tasks=("high_cps_flag", "sum"),
    cps_eligible=("cps_eligible", "sum")
)

# 6. Calculate warning rates (%)
users["blank_rate"] = (
    100 * users["blank_tasks"]
    / users["blank_eligible"].replace(0, np.nan)
)

users["ter_below_1_rate"] = (
    100 * users["ter_below_1_tasks"]
    / users["ter_eligible"].replace(0, np.nan)
)

users["extreme_ter_rate"] = (
    100 * users["extreme_ter_tasks"]
    / users["ter_eligible"].replace(0, np.nan)
)

users["high_cps_rate"] = (
    100 * users["high_cps_tasks"]
    / users["cps_eligible"].replace(0, np.nan)
)

# 7. Final proposed blocking conditions
MIN_TASKS = 20
BLANK_THRESHOLD = 2.81
LOW_TER_THRESHOLD = 30.0

users["block_candidate"] = (
    (users["total_tasks"] >= MIN_TASKS)
    & (users["blank_rate"] > BLANK_THRESHOLD)
    & (users["ter_below_1_rate"] > LOW_TER_THRESHOLD)
)

# 8. Display results
columns = [
    "total_tasks",
    "blank_tasks",
    "blank_rate",
    "ter_below_1_tasks",
    "ter_below_1_rate",
    "extreme_ter_rate",
    "high_cps_rate",
    "block_candidate"
]

result = users.sort_values(
    ["block_candidate", "blank_rate", "ter_below_1_rate"],
    ascending=[False, False, False]
)

print("FINAL BLOCKING RULE")
print(f"Minimum tasks: {MIN_TASKS}")
print(f"Blank rate > {BLANK_THRESHOLD}%")
print(f"TER < 1 rate > {LOW_TER_THRESHOLD}%")

print("\nTRANSCRIBER RESULTS")
display(result[columns].round(2))

print("\nBLOCK CANDIDATES")
display(result.loc[result["block_candidate"], columns].round(2))

print(
    "\nTotal block candidates:",
    int(users["block_candidate"].sum())
)

# 9. Save outputs
output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)

result[columns].to_csv(
    output_dir / "final_transcriber_block_analysis.csv"
)

print("\nSaved:", output_dir / "final_transcriber_block_analysis.csv")

FINAL BLOCKING RULE
Minimum tasks: 20
Blank rate > 2.81%
TER < 1 rate > 30.0%

TRANSCRIBER RESULTS

,total_tasks,blank_tasks,blank_rate,ter_below_1_tasks,ter_below_1_rate,extreme_ter_rate,high_cps_rate,block_candidate
user_id,,,,,,,,
326611,149,2,3.28,35,40.7,0.0,0.0,True
71040194,1,1,100.00,1,100.0,0.0,NaN,False
71042597,1,1,100.00,1,100.0,0.0,NaN,False
71042890,1,1,100.00,1,100.0,0.0,NaN,False
71047782,1,1,100.00,1,100.0,0.0,NaN,False
...,...,...,...,...,...,...,...,...
75217521,1,0,NaN,0,NaN,NaN,NaN,False
75218016,1,0,NaN,0,NaN,NaN,NaN,False
75248935,1,0,NaN,0,NaN,NaN,NaN,False
75258168,1,0,NaN,0,NaN,NaN,NaN,False
75264621,1,0,NaN,0,NaN,NaN,NaN,False

BLOCK CANDIDATES

,total_tasks,blank_tasks,blank_rate,ter_below_1_tasks,ter_below_1_rate,extreme_ter_rate,high_cps_rate,block_candidate
user_id,,,,,,,,
326611,149,2,3.28,35,40.7,0.0,0.0,True

Total block candidates: 1

Saved: ..\outputs\final_transcriber_block_analysis.csv

In [72]:
import pandas as pd
import numpy as np
from pathlib import Path

df = pd.read_csv("../data/raw/transcription_data.csv")

df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

text = df["user_text"].fillna("").astype(str).str.strip()
whisper = df["whisper_text"].fillna("").astype(str).str.strip()

df["ter"] = (
    df["time_taken_by_user"]
    / df["duration"].where(df["duration"] > 0)
)

df["char_count"] = text.apply(
    lambda x: 0 if x.lower() in ("", "[blank]")
    else sum(not c.isspace() for c in x)
)

df["cps"] = (
    df["char_count"]
    / df["time_taken_by_user"].where(df["time_taken_by_user"] > 0)
)

# Task-level signals
df["blank_flag"] = (
    text.str.lower().isin(["", "[blank]"])
    & (whisper != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < 0.1787571047)
    & (df["duration"] > 1)
)

df["high_cps_flag"] = (
    (df["cps"] > 59.858)
    & (df["duration"] > 5)
)

df["ter_below_1_flag"] = (
    (df["ter"] < 1)
    & (df["duration"] > 1)
)

# Aggregate at transcriber level
users = df.groupby("user_id").agg(
    total_tasks=("user_id", "size"),
    blank_tasks=("blank_flag", "sum"),
    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    high_cps_tasks=("high_cps_flag", "sum"),
    ter_below_1_tasks=("ter_below_1_flag", "sum")
)

# Use a consistent denominator: total tasks
for signal in [
    "blank",
    "extreme_ter",
    "high_cps",
    "ter_below_1"
]:
    users[f"{signal}_rate"] = (
        100 * users[f"{signal}_tasks"] / users["total_tasks"]
    )

# Proposed conservative candidate rule, not proof of abuse
MIN_TASKS = 20

users["block_candidate"] = (
    (users["total_tasks"] >= MIN_TASKS)
    & (users["blank_tasks"] >= 3)
    & (users["extreme_ter_tasks"] >= 3)
    & (users["high_cps_tasks"] >= 3)
)

columns = [
    "total_tasks",
    "blank_tasks", "blank_rate",
    "extreme_ter_tasks", "extreme_ter_rate",
    "high_cps_tasks", "high_cps_rate",
    "ter_below_1_tasks", "ter_below_1_rate",
    "block_candidate"
]

result = users.sort_values(
    ["block_candidate", "extreme_ter_tasks", "high_cps_tasks"],
    ascending=[False, False, False]
)

display(result[columns].round(2))

print("Block candidates:", int(users["block_candidate"].sum()))

output_dir = Path("../outputs")
output_dir.mkdir(parents=True, exist_ok=True)

result[columns].to_csv(
    output_dir / "corrected_transcriber_analysis.csv"
)

,total_tasks,blank_tasks,blank_rate,extreme_ter_tasks,extreme_ter_rate,high_cps_tasks,high_cps_rate,ter_below_1_tasks,ter_below_1_rate,block_candidate
user_id,,,,,,,,,,
71039477,1,0,0.0,1,100.0,1,100.0,1,100.0,False
71039528,1,0,0.0,1,100.0,1,100.0,1,100.0,False
71041236,1,0,0.0,1,100.0,1,100.0,1,100.0,False
71043852,1,0,0.0,1,100.0,1,100.0,1,100.0,False
71044053,1,0,0.0,1,100.0,1,100.0,1,100.0,False
...,...,...,...,...,...,...,...,...,...,...
75315875,1,0,0.0,0,0.0,0,0.0,0,0.0,False
75319972,1,0,0.0,0,0.0,0,0.0,0,0.0,False
75325959,1,0,0.0,0,0.0,0,0.0,0,0.0,False
75325974,1,0,0.0,0,0.0,0,0.0,0,0.0,False
75326070,1,0,0.0,0,0.0,0,0.0,0,0.0,False

Block candidates: 0

In [73]:
users["block_candidate"] = (
    (users["total_tasks"] >= 20)
    & (
        (users["blank_rate"] > 2)
        | (users["ter_below_1_rate"] > 30)
    )
    & (
        (users["extreme_ter_rate"] > 0)
        | (users["high_cps_rate"] > 0)
    )
)

In [74]:

import pandas as pd
import numpy as np
from pathlib import Path

# ==================================================
# 1. LOAD DATA
# ==================================================
DATA_PATH = "../data/raw/transcription_data.csv"
OUTPUT_DIR = Path("../outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(DATA_PATH)

required_cols = [
    "user_id",
    "whisper_text",
    "user_text",
    "is_edited",
    "duration",
    "time_taken_by_user",
]

missing_cols = [col for col in required_cols if col not in df.columns]
if missing_cols:
    raise ValueError(f"Missing columns: {missing_cols}")

# ==================================================
# 2. CLEAN DATA AND CALCULATE METRICS
# ==================================================
df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

df["whisper_text"] = df["whisper_text"].fillna("").astype(str).str.strip()
df["user_text"] = df["user_text"].fillna("").astype(str).str.strip()

df["is_blank"] = (
    df["user_text"].str.lower().isin(["", "[blank]"])
)

# TER here means task time / audio duration.
df["ter"] = np.where(
    (df["duration"] > 0) & (df["time_taken_by_user"] >= 0),
    df["time_taken_by_user"] / df["duration"],
    np.nan,
)

# CPS = non-whitespace transcript characters / task time.
df["transcript_chars"] = df["user_text"].apply(
    lambda text: 0 if text.lower() == "[blank]"
    else sum(not char.isspace() for char in text)
)

df["cps"] = np.where(
    df["time_taken_by_user"] > 0,
    df["transcript_chars"] / df["time_taken_by_user"],
    np.nan,
)

# ==================================================
# 3. TASK-LEVEL WARNING FLAGS
# ==================================================
MIN_DURATION_TER = 1
MIN_DURATION_CPS = 5

EXTREME_TER_THRESHOLD = 0.1787571047
HIGH_CPS_THRESHOLD = 59.858

df["blank_flag"] = (
    df["is_blank"]
    & (df["whisper_text"] != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < EXTREME_TER_THRESHOLD)
    & (df["duration"] > MIN_DURATION_TER)
)

df["ter_below_1_flag"] = (
    (df["ter"] < 1)
    & (df["duration"] > MIN_DURATION_TER)
)

df["high_cps_flag"] = (
    (df["cps"] > HIGH_CPS_THRESHOLD)
    & (df["duration"] > MIN_DURATION_CPS)
)

# ==================================================
# 4. AGGREGATE BY TRANSCRIBER
# ==================================================
# Use eligible tasks as denominators for each warning rate.
df["blank_eligible"] = (
    (df["duration"] > 1)
    & (df["whisper_text"] != "")
)

df["ter_eligible"] = (
    (df["duration"] > MIN_DURATION_TER)
    & df["ter"].notna()
)

df["cps_eligible"] = (
    (df["duration"] > MIN_DURATION_CPS)
    & df["cps"].notna()
)

users = df.groupby("user_id", dropna=False).agg(
    total_tasks=("user_id", "size"),

    blank_tasks=("blank_flag", "sum"),
    blank_eligible_tasks=("blank_eligible", "sum"),

    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    ter_below_1_tasks=("ter_below_1_flag", "sum"),
    ter_eligible_tasks=("ter_eligible", "sum"),

    high_cps_tasks=("high_cps_flag", "sum"),
    cps_eligible_tasks=("cps_eligible", "sum"),
).reset_index()

# Rates are percentages from 0 to 100.
def percentage(numerator, denominator):
    return np.where(
        denominator > 0,
        numerator / denominator * 100,
        0.0,
    )

users["blank_rate"] = percentage(
    users["blank_tasks"], users["blank_eligible_tasks"]
)

users["extreme_ter_rate"] = percentage(
    users["extreme_ter_tasks"], users["ter_eligible_tasks"]
)

users["ter_below_1_rate"] = percentage(
    users["ter_below_1_tasks"], users["ter_eligible_tasks"]
)

users["high_cps_rate"] = percentage(
    users["high_cps_tasks"], users["cps_eligible_tasks"]
)

# ==================================================
# 5. BLOCK-CANDIDATE RULE
# ==================================================
MIN_TASKS = 20
BLANK_RATE_THRESHOLD = 2.0
TER_BELOW_1_RATE_THRESHOLD = 30.0

users["block_candidate"] = (
    (users["total_tasks"] >= MIN_TASKS)
    & (users["blank_rate"] > BLANK_RATE_THRESHOLD)
    & (users["ter_below_1_rate"] > TER_BELOW_1_RATE_THRESHOLD)
)

# Explain why each user is flagged.
users["candidate_reason"] = np.select(
    [
        users["block_candidate"],
        users["total_tasks"] < MIN_TASKS,
    ],
    [
        "High blank rate + high TER<1 rate",
        "Insufficient task history",
    ],
    default="Does not meet blocking rule",
)

# ==================================================
# 6. DISPLAY RESULTS
# ==================================================
display_cols = [
    "user_id",
    "total_tasks",
    "blank_tasks",
    "blank_eligible_tasks",
    "blank_rate",
    "ter_below_1_tasks",
    "ter_eligible_tasks",
    "ter_below_1_rate",
    "extreme_ter_tasks",
    "extreme_ter_rate",
    "high_cps_tasks",
    "high_cps_rate",
    "block_candidate",
    "candidate_reason",
]

users = users.sort_values(
    ["block_candidate", "total_tasks"],
    ascending=[False, False],
)

print("Total tasks:", len(df))
print("Unique transcribers:", df["user_id"].nunique())
print("Block candidates:", int(users["block_candidate"].sum()))

display(users[display_cols].head(50))

# ==================================================
# 7. SAVE OUTPUTS
# ==================================================
users[display_cols].to_csv(
    OUTPUT_DIR / "transcriber_risk_summary.csv",
    index=False,
)

users.loc[users["block_candidate"], display_cols].to_csv(
    OUTPUT_DIR / "block_candidates.csv",
    index=False,
)

df.to_csv(
    OUTPUT_DIR / "task_level_warning_flags.csv",
    index=False,
)

print("\nSaved files:")
print(OUTPUT_DIR / "transcriber_risk_summary.csv")
print(OUTPUT_DIR / "block_candidates.csv")
print(OUTPUT_DIR / "task_level_warning_flags.csv")

Total tasks: 51783
Unique transcribers: 48875
Block candidates: 3

,user_id,total_tasks,blank_tasks,blank_eligible_tasks,blank_rate,ter_below_1_tasks,ter_eligible_tasks,ter_below_1_rate,extreme_ter_tasks,extreme_ter_rate,high_cps_tasks,high_cps_rate,block_candidate,candidate_reason
6,580062,609,7,314,2.229299,164,387,42.377261,0,0.0,0,0.0,True,High blank rate + high TER<1 rate
7,632098,165,2,90,2.222222,54,104,51.923077,0,0.0,0,0.0,True,High blank rate + high TER<1 rate
2,326611,149,2,61,3.278689,35,86,40.697674,0,0.0,0,0.0,True,High blank rate + high TER<1 rate
3,393886,509,4,245,1.632653,123,298,41.275168,0,0.0,0,0.0,False,Does not meet blocking rule
8,681509,358,1,190,0.526316,99,239,41.422594,0,0.0,0,0.0,False,Does not meet blocking rule
4,410566,349,0,181,0.000000,105,226,46.460177,0,0.0,0,0.0,False,Does not meet blocking rule
0,222099,333,0,176,0.000000,89,217,41.013825,0,0.0,0,0.0,False,Does not meet blocking rule
1,311760,184,0,96,0.000000,57,126,45.238095,0,0.0,0,0.0,False,Does not meet blocking rule
5,467270,176,0,98,0.000000,50,121,41.322314,0,0.0,0,0.0,False,Does not meet blocking rule
9,688393,86,0,43,0.000000,27,52,51.923077,0,0.0,0,0.0,False,Does not meet blocking rule
10,56540996,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
11,56567509,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
12,56567516,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
13,56567685,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
14,56567699,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
15,56567741,1,0,0,0.000000,1,1,100.000000,0,0.0,0,0.0,False,Insufficient task history
16,56567807,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
17,56567808,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
18,56568519,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
19,56568526,1,0,0,0.000000,1,1,100.000000,0,0.0,0,0.0,False,Insufficient task history
20,56568534,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
21,56568590,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
22,56568601,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
23,56568610,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
24,56568666,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
25,56568674,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
26,56568700,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
27,56568715,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
28,56568738,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
29,56568773,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
30,56568799,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
31,56569066,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
32,56569245,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
33,56569446,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
34,56569566,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
35,56569621,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
36,56569632,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
37,56569725,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
38,56569780,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
39,56569831,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
40,56570228,1,0,0,0.000000,0,0,0.000000,0,0.0,0,0.0,False,Insufficient task history
41,56570387,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
42,56570477,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
43,56570534,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
44,56570627,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
45,56570687,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
46,56570863,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
47,56571083,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
48,56571134,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history
49,56571629,1,0,0,0.000000,0,1,0.000000,0,0.0,0,0.0,False,Insufficient task history

Saved files:
..\outputs\transcriber_risk_summary.csv
..\outputs\block_candidates.csv
..\outputs\task_level_warning_flags.csv

In [75]:

# ==================================================
# 5. TRANSCRIBER-LEVEL BLOCKING RULE
# ==================================================
MIN_TASKS = 5

BLANK_RATE_THRESHOLD = 2.0
TER_BELOW_1_RATE_THRESHOLD = 30.0

# All rates are percentages (0–100).
# Ensure these counts and rates were calculated in Section 4.
users["blank_rate"] = np.where(
    users["blank_eligible_tasks"] > 0,
    100 * users["blank_tasks"] / users["blank_eligible_tasks"],
    0.0,
)

users["extreme_ter_rate"] = np.where(
    users["ter_eligible_tasks"] > 0,
    100 * users["extreme_ter_tasks"] / users["ter_eligible_tasks"],
    0.0,
)

users["ter_below_1_rate"] = np.where(
    users["ter_eligible_tasks"] > 0,
    100 * users["ter_below_1_tasks"] / users["ter_eligible_tasks"],
    0.0,
)

users["high_cps_rate"] = np.where(
    users["cps_eligible_tasks"] > 0,
    100 * users["high_cps_tasks"] / users["cps_eligible_tasks"],
    0.0,
)

# Keep the original statistically derived task-level thresholds:
# Extreme TER < 0.1787571047
# High CPS > 59.858

# Candidate if either blank rate or TER<1 rate crosses its threshold,
# OR if extreme TER or high CPS occurs.
users["block_candidate"] = (
    (users["total_tasks"] >= MIN_TASKS)
    & (
        (users["blank_rate"] > BLANK_RATE_THRESHOLD)
        | (users["ter_below_1_rate"] > TER_BELOW_1_RATE_THRESHOLD)
        | (users["extreme_ter_rate"] > 0)
        | (users["high_cps_rate"] > 0)
    )
)

users["candidate_reason"] = np.select(
    [
        (users["extreme_ter_rate"] > 0)
        & (users["high_cps_rate"] > 0),

        users["extreme_ter_rate"] > 0,

        users["high_cps_rate"] > 0,

        (users["blank_rate"] > BLANK_RATE_THRESHOLD)
        & (users["ter_below_1_rate"] > TER_BELOW_1_RATE_THRESHOLD),

        users["blank_rate"] > BLANK_RATE_THRESHOLD,

        users["ter_below_1_rate"] > TER_BELOW_1_RATE_THRESHOLD,
    ],
    [
        "Extreme TER + high CPS",
        "Extreme TER",
        "High CPS",
        "High blank rate + high TER<1 rate",
        "High blank rate",
        "High TER<1 rate",
    ],
    default="No warning threshold crossed",
)

# ==================================================
# 6. DISPLAY AND SAVE
# ==================================================
result_cols = [
    "user_id",
    "total_tasks",
    "blank_tasks",
    "blank_rate",
    "ter_below_1_tasks",
    "ter_below_1_rate",
    "extreme_ter_tasks",
    "extreme_ter_rate",
    "high_cps_tasks",
    "high_cps_rate",
    "block_candidate",
    "candidate_reason",
]

users = users.sort_values(
    ["block_candidate", "total_tasks"],
    ascending=[False, False],
)

print("Total transcribers:", len(users))
print("Transcribers with 5+ tasks:", (users["total_tasks"] >= 5).sum())
print("Block candidates:", int(users["block_candidate"].sum()))

display(users[result_cols])

users[result_cols].to_csv(
    OUTPUT_DIR / "transcriber_risk_summary.csv",
    index=False,
)

users.loc[users["block_candidate"], result_cols].to_csv(
    OUTPUT_DIR / "block_candidates.csv",
    index=False,
)

Total transcribers: 48875
Transcribers with 5+ tasks: 10
Block candidates: 10

,user_id,total_tasks,blank_tasks,blank_rate,ter_below_1_tasks,ter_below_1_rate,extreme_ter_tasks,extreme_ter_rate,high_cps_tasks,high_cps_rate,block_candidate,candidate_reason
6,580062,609,7,2.229299,164,42.377261,0,0.0,0,0.0,True,High blank rate + high TER<1 rate
3,393886,509,4,1.632653,123,41.275168,0,0.0,0,0.0,True,High TER<1 rate
8,681509,358,1,0.526316,99,41.422594,0,0.0,0,0.0,True,High TER<1 rate
4,410566,349,0,0.000000,105,46.460177,0,0.0,0,0.0,True,High TER<1 rate
0,222099,333,0,0.000000,89,41.013825,0,0.0,0,0.0,True,High TER<1 rate
...,...,...,...,...,...,...,...,...,...,...,...,...
48870,75315875,1,0,0.000000,0,0.000000,0,0.0,0,0.0,False,No warning threshold crossed
48871,75319972,1,0,0.000000,0,0.000000,0,0.0,0,0.0,False,No warning threshold crossed
48872,75325959,1,0,0.000000,0,0.000000,0,0.0,0,0.0,False,No warning threshold crossed
48873,75325974,1,0,0.000000,0,0.000000,0,0.0,0,0.0,False,No warning threshold crossed
48874,75326070,1,0,0.000000,0,0.000000,0,0.0,0,0.0,False,No warning threshold crossed

In [76]:

import pandas as pd
import numpy as np
from pathlib import Path

# =========================================================
# 1. CONFIGURATION
# =========================================================
DATA_PATH = "../data/raw/transcription_data.csv"
OUTPUT_DIR = Path("../outputs")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

MIN_TASKS = 5

# Existing task-level thresholds
EXTREME_TER_THRESHOLD = 0.1787571047
HIGH_CPS_THRESHOLD = 59.858

# Transcriber-level thresholds (percentages)
BLANK_RATE_THRESHOLD = 2.0
TER_BELOW_1_RATE_THRESHOLD = 30.0

# =========================================================
# 2. LOAD DATA
# =========================================================
df = pd.read_csv(DATA_PATH)

required_cols = [
    "user_id",
    "whisper_text",
    "user_text",
    "is_edited",
    "duration",
    "time_taken_by_user",
]

missing_cols = [c for c in required_cols if c not in df.columns]
if missing_cols:
    raise ValueError(f"Missing required columns: {missing_cols}")

df["duration"] = pd.to_numeric(df["duration"], errors="coerce")
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)

for col in ["whisper_text", "user_text"]:
    df[col] = df[col].fillna("").astype(str).str.strip()

# =========================================================
# 3. TASK-LEVEL METRICS
# =========================================================
df["is_blank"] = df["user_text"].str.lower().isin(["", "[blank]"])

# TER used here = task time / audio duration
df["ter"] = np.where(
    (df["duration"] > 0) & (df["time_taken_by_user"] >= 0),
    df["time_taken_by_user"] / df["duration"],
    np.nan,
)

# CPS = non-whitespace transcript characters / task time
df["transcript_chars"] = df["user_text"].apply(
    lambda text: (
        0 if text.lower() == "[blank]"
        else sum(not char.isspace() for char in text)
    )
)

df["cps"] = np.where(
    df["time_taken_by_user"] > 0,
    df["transcript_chars"] / df["time_taken_by_user"],
    np.nan,
)

# =========================================================
# 4. DEFINE WARNING SIGNALS
# =========================================================
df["blank_eligible"] = (
    (df["duration"] > 1)
    & (df["whisper_text"] != "")
)

df["ter_eligible"] = (
    (df["duration"] > 1)
    & df["ter"].notna()
)

df["cps_eligible"] = (
    (df["duration"] > 5)
    & df["cps"].notna()
)

df["blank_flag"] = (
    df["is_blank"]
    & (df["whisper_text"] != "")
    & (df["duration"] > 1)
)

df["extreme_ter_flag"] = (
    (df["ter"] < EXTREME_TER_THRESHOLD)
    & (df["duration"] > 1)
)

df["ter_below_1_flag"] = (
    (df["ter"] < 1)
    & (df["duration"] > 1)
)

df["high_cps_flag"] = (
    (df["cps"] > HIGH_CPS_THRESHOLD)
    & (df["duration"] > 5)
)

# =========================================================
# 5. AGGREGATE BY TRANSCRIBER
# =========================================================
users = df.groupby("user_id", dropna=False).agg(
    total_tasks=("user_id", "size"),

    blank_tasks=("blank_flag", "sum"),
    blank_eligible_tasks=("blank_eligible", "sum"),

    extreme_ter_tasks=("extreme_ter_flag", "sum"),
    ter_below_1_tasks=("ter_below_1_flag", "sum"),
    ter_eligible_tasks=("ter_eligible", "sum"),

    high_cps_tasks=("high_cps_flag", "sum"),
    cps_eligible_tasks=("cps_eligible", "sum"),
).reset_index()


def percentage(count, eligible):
    return np.where(
        eligible > 0,
        count / np.maximum(eligible, 1) * 100,
        0.0,
    )


users["blank_rate"] = percentage(
    users["blank_tasks"],
    users["blank_eligible_tasks"],
)

users["extreme_ter_rate"] = percentage(
    users["extreme_ter_tasks"],
    users["ter_eligible_tasks"],
)

users["ter_below_1_rate"] = percentage(
    users["ter_below_1_tasks"],
    users["ter_eligible_tasks"],
)

users["high_cps_rate"] = percentage(
    users["high_cps_tasks"],
    users["cps_eligible_tasks"],
)

# =========================================================
# 6. RELAXED BLOCK-CANDIDATE RULE
# =========================================================
# Four warning signals:
# 1. Blank rate > 2%
# 2. Extreme TER rate > 0%
# 3. High CPS rate > 0%
# 4. TER-below-1 rate > 30%
#
# Candidate requires at least 5 tasks and 2+ signals.
# These are review candidates, not confirmed fraud.

users["blank_signal"] = (
    users["blank_rate"] > BLANK_RATE_THRESHOLD
)

users["extreme_ter_signal"] = (
    users["extreme_ter_rate"] > 0
)

users["high_cps_signal"] = (
    users["high_cps_rate"] > 0
)

users["ter_below_1_signal"] = (
    users["ter_below_1_rate"] > TER_BELOW_1_RATE_THRESHOLD
)

signal_cols = [
    "blank_signal",
    "extreme_ter_signal",
    "high_cps_signal",
    "ter_below_1_signal",
]

users["warning_signal_count"] = (
    users[signal_cols].sum(axis=1)
)

users["block_candidate"] = (
    (users["total_tasks"] >= MIN_TASKS)
    & (users["warning_signal_count"] >= 2)
)

users["candidate_reason"] = users.apply(
    lambda row: ", ".join(
        label
        for col, label in [
            ("blank_signal", "High blank rate"),
            ("extreme_ter_signal", "Extreme TER"),
            ("high_cps_signal", "High CPS"),
            ("ter_below_1_signal", "High TER<1 rate"),
        ]
        if row[col]
    ) if row["block_candidate"] else "Does not meet rule",
    axis=1,
)

# =========================================================
# 7. SUMMARY AND RESULTS
# =========================================================
result_cols = [
    "user_id",
    "total_tasks",
    "blank_tasks",
    "blank_eligible_tasks",
    "blank_rate",
    "ter_below_1_tasks",
    "ter_eligible_tasks",
    "ter_below_1_rate",
    "extreme_ter_tasks",
    "extreme_ter_rate",
    "high_cps_tasks",
    "cps_eligible_tasks",
    "high_cps_rate",
    "warning_signal_count",
    "candidate_reason",
    "block_candidate",
]

users = users.sort_values(
    ["block_candidate", "warning_signal_count", "total_tasks"],
    ascending=[False, False, False],
)

print("=" * 55)
print("TRANSCRIBER RISK SUMMARY")
print("=" * 55)
print(f"Total task rows: {len(df):,}")
print(f"Unique transcribers: {df['user_id'].nunique():,}")
print(f"Transcribers with >= {MIN_TASKS} tasks: "
      f"{(users['total_tasks'] >= MIN_TASKS).sum():,}")
print(f"Block candidates for review: "
      f"{users['block_candidate'].sum():,}")

print("\nWarning-signal counts:")
for col in signal_cols:
    print(f"{col}: {int(users[col].sum()):,}")

print("\nCandidate list:")
display(users.loc[users["block_candidate"], result_cols])

print("\nTop 30 transcribers by warning signals:")
display(users[result_cols].head(30))

# =========================================================
# 8. SAVE OUTPUT FILES
# =========================================================
users[result_cols].to_csv(
    OUTPUT_DIR / "transcriber_risk_summary.csv",
    index=False,
)

users.loc[users["block_candidate"], result_cols].to_csv(
    OUTPUT_DIR / "block_candidates.csv",
    index=False,
)

df.to_csv(
    OUTPUT_DIR / "task_level_warning_flags.csv",
    index=False,
)

print("\nFiles saved:")
print(OUTPUT_DIR / "transcriber_risk_summary.csv")
print(OUTPUT_DIR / "block_candidates.csv")
print(OUTPUT_DIR / "task_level_warning_flags.csv")

=======================================================
TRANSCRIBER RISK SUMMARY
=======================================================
Total task rows: 51,783
Unique transcribers: 48,875
Transcribers with >= 5 tasks: 10
Block candidates for review: 3

Warning-signal counts:
blank_signal: 1,009
extreme_ter_signal: 517
high_cps_signal: 457
ter_below_1_signal: 5,146

Candidate list:

,user_id,total_tasks,blank_tasks,blank_eligible_tasks,blank_rate,ter_below_1_tasks,ter_eligible_tasks,ter_below_1_rate,extreme_ter_tasks,extreme_ter_rate,high_cps_tasks,cps_eligible_tasks,high_cps_rate,warning_signal_count,candidate_reason,block_candidate
6,580062,609,7,314,2.229299,164,387,42.377261,0,0.0,0,233,0.0,2,"High blank rate, High TER<1 rate",True
7,632098,165,2,90,2.222222,54,104,51.923077,0,0.0,0,73,0.0,2,"High blank rate, High TER<1 rate",True
2,326611,149,2,61,3.278689,35,86,40.697674,0,0.0,0,54,0.0,2,"High blank rate, High TER<1 rate",True

Top 30 transcribers by warning signals:

,user_id,total_tasks,blank_tasks,blank_eligible_tasks,blank_rate,ter_below_1_tasks,ter_eligible_tasks,ter_below_1_rate,extreme_ter_tasks,extreme_ter_rate,high_cps_tasks,cps_eligible_tasks,high_cps_rate,warning_signal_count,candidate_reason,block_candidate
6,580062,609,7,314,2.229299,164,387,42.377261,0,0.0,0,233,0.0,2,"High blank rate, High TER<1 rate",True
7,632098,165,2,90,2.222222,54,104,51.923077,0,0.0,0,73,0.0,2,"High blank rate, High TER<1 rate",True
2,326611,149,2,61,3.278689,35,86,40.697674,0,0.0,0,54,0.0,2,"High blank rate, High TER<1 rate",True
4467,71039477,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4477,71039528,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4584,71041236,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4733,71043852,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4753,71044053,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4754,71044058,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4767,71044420,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4844,71046140,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4920,71048171,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4926,71048210,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
4980,71048821,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
5066,71049934,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
5323,71122999,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
5457,71124901,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
5458,71124903,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
5896,71131136,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
7228,71277583,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
7536,71281446,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
7911,71347643,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
7944,71347911,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
8521,71354662,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
8626,71356411,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
8627,71356412,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
8635,71356452,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
8670,71356901,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
8685,71357034,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False
9047,71412728,1,0,1,0.000000,1,1,100.000000,1,100.0,1,1,100.0,3,Does not meet rule,False

Files saved:
..\outputs\transcriber_risk_summary.csv
..\outputs\block_candidates.csv
..\outputs\task_level_warning_flags.csv

In [1]:

import pandas as pd

# Load dataset
df = pd.read_csv("../data/raw/transcription_data.csv")

# Count tasks completed by each transcriber
tasks_per_user = df.groupby("user_id").size()

# Calculate distribution
total_tasks = len(df)
total_users = tasks_per_user.nunique()  # overwritten below intentionally? No

total_users = len(tasks_per_user)
single_task_users = (tasks_per_user == 1).sum()
five_plus_users = (tasks_per_user >= 5).sum()
ten_plus_users = (tasks_per_user >= 10).sum()

print("=" * 45)
print("TRANSCRIBER ACTIVITY DISTRIBUTION")
print("=" * 45)

print(f"Total task records       : {total_tasks:,}")
print(f"Unique transcribers      : {total_users:,}")
print(
    f"Users with 1 task        : {single_task_users:,} "
    f"({single_task_users / total_users * 100:.2f}%)"
)
print(
    f"Users with 5+ tasks      : {five_plus_users:,} "
    f"({five_plus_users / total_users * 100:.4f}%)"
)
print(
    f"Users with 10+ tasks     : {ten_plus_users:,} "
    f"({ten_plus_users / total_users * 100:.4f}%)"
)

print("=" * 45)

=============================================
TRANSCRIBER ACTIVITY DISTRIBUTION
=============================================
Total task records       : 51,783
Unique transcribers      : 48,875
Users with 1 task        : 48,865 (99.98%)
Users with 5+ tasks      : 10 (0.0205%)
Users with 10+ tasks     : 10 (0.0205%)
=============================================

In [ ]:
# Convert columns to numeric
df["time_taken_by_user"] = pd.to_numeric(
    df["time_taken_by_user"], errors="coerce"
)
df["duration"] = pd.to_numeric(
    df["duration"], errors="coerce"
)

# Clean user transcript
user_text = df["user_text"].fillna("").astype(str).str.strip()

# Exclude empty text and [blank] submissions
valid_text = (
    user_text.ne("")
    & user_text.str.lower().ne("[blank]")
)

# Count non-whitespace characters
df["character_count"] = user_text.str.replace(
    r"\s+", "", regex=True
).str.len()

# Identify valid tasks with audio longer than 5 seconds
valid = (
    df["time_taken_by_user"].gt(0)
    & df["time_taken_by_user"].notna()
    & df["duration"].gt(5)
    & df["duration"].notna()
    & valid_text
)

# Calculate characters per second
df["CPS"] = np.nan
df.loc[valid, "CPS"] = (
    df.loc[valid, "character_count"]
    / df.loc[valid, "time_taken_by_user"]
)

# Apply our experimentally derived threshold
high_cps_threshold = 59.858

df["flag_high_throughput"] = (
    valid & (df["CPS"] > high_cps_threshold)
)

print(
    "High-throughput tasks:",
    int(df["flag_high_throughput"].sum())
)

print(
    "Percentage of all tasks:",
    round(df["flag_high_throughput"].mean() * 100, 2),
    "%"
)